import {catalog,calculate,createProgram,validateRows} from './domain.mjs';
import {METHODOLOGY_VERSION} from '../methodology.mjs';
// Public format demonstration: synthetic data only, never an approved audit file.
export function presentationExample(context={}){
 const engagement={client:'Empresa de ejemplo · DATOS FICTICIOS',year:2025,cutoff:'2025-12-31',firm:'Audit Consulting Group',preparer:'Preparador de demostración',reviewer:'Revisor de demostración',framework:'NIIF completas',country:'Ecuador',currency:'USD',visit:'Final',edition:'2025 · verificar aplicabilidad',adoption:'Pendiente de verificación para un encargo real',reuseScope:'one',...context};
 const source=engagement.framework==='NIIF para las PYMES'?{organization:'IFRS Foundation',document:'NIIF para las PYMES · Inventarios · edición por verificar',url:'https://www.ifrs.org/issued-standards/ifrs-for-smes/'}:catalog.vnr.source;
 const definition={...catalog.vnr,source};
 const rows=[['0001','Producto de ejemplo A','10','20','18','1','2'],['0002','Producto de ejemplo B','5','30','40','1','2'],['0003','Producto de ejemplo C','8','15','13','1','1']].map((v,i)=>({...Object.fromEntries(['id','description','quantity','unit_cost','selling_price','completion_cost','selling_cost'].map((k,j)=>[k,v[j]])),recorded_allowance:'0',_file:'datos_ficticios.csv',_sheet:'Ejemplo',_row:i+2}));
 return {id:'ejemplo',demo:true,state:'DEMOSTRACIÓN',version:2,methodologyVersion:METHODOLOGY_VERSION,country:engagement.country,engagement,definition,rows,parameters:{},run:calculate(catalog.vnr,rows),validation:validateRows(catalog.vnr,rows),reconciliation:{ledger:'470',difference:'0',tolerance:'0',within:true},program:createProgram(definition,engagement),sources:[{category:'Contable',...source,section:'Pendiente de verificación para un encargo real',date:'',verified:false},{category:'NIA',organization:'IAASB',document:'NIA aplicables a evidencia y estimaciones · identificar versión',section:'Investigación pendiente',date:'',url:'https://www.iaasb.org/',verified:false}],events:[],notes:[],analysis:'Demostración de formato con tres partidas ficticias. No corresponde a un encargo real.',exceptionReview:'Pendiente de revisión profesional en un encargo real.',conclusion:'EJEMPLO DE PRESENTACIÓN. Los importes ilustran el funcionamiento de las fórmulas. No constituye una conclusión de auditoría. Impuesto diferido y reversos requieren bases fiscales, tasa sustentada, evidencia y evaluación del marco; este ejemplo no los determina automáticamente.',conclusionReviewed:false};
}
