import data from './demoCase.json';
export {data as DEMO};
export const DEMO_POLICY='EJEMPLO DIDÁCTICO · DATOS FICTICIOS\nPoblación: tres productos ordinarios al 31/12/2026, evaluados individualmente al menor entre costo y VNR. Precio menos costos necesarios de terminación y venta.\nProducto DEMO-B: se supone recuperación del precio sustentada por ventas posteriores ficticias; revertir los 40 registrados.\nNo se evalúa impuesto diferido en este primer ejercicio. No representa política aprobada ni dictamen.\nMayor de inventarios: 940 USD; deterioro registrado: 65 USD; tolerancia: 0.01 USD.\nResultado esperado: deterioro 110; gasto adicional 85; reversión 40; ajuste neto 45; valor contable 830.\nPara una prueba real, sustituir los datos, obtener evidencia y verificar marco, edición y adopción local.';
export function demoContext(framework){return {client:'DEMO · Comercial Ejemplo (ficticia)',country:'Ecuador',currency:'USD',year:'2026',cutoff:'2026-12-31',visit:'Final',preparer:'Preparador DEMO',reviewer:'Revisor DEMO',firm:'audit_consulting',framework,edition:framework==='sme'?'2015':'2026',adoption:'SUPUESTO DIDÁCTICO: verificar adopción y vigencia antes de usar datos reales.',reuse_scope:'one',selected_tests:''};}
export function demoPolicy(framework){return {basis:'EJEMPLO: tres productos ordinarios al corte, medidos individualmente al menor entre costo y VNR. Se descuentan costos necesarios de terminación y venta.',normative_reference:framework==='sme'?'EJEMPLO para revisar: NIIF para las PYMES, secciones 13 y 27; edición 2015 como supuesto didáctico. Documentar vigencia local.':'EJEMPLO para revisar: NIC 2, párrafos 9 y 28–34. Documentar edición y vigencia local.',reversal_basis:'SUPUESTO DEMO-B: ventas posteriores ficticias confirman recuperación del precio; reversión de 40, limitada al deterioro previo.',selling_method:'unit',reviewed:false,evidence_reviewed:false,eligible_expenses:'',sales_base:'',allocation_basis:''};}
export async function exampleFile(slot,blank=false){
 if(slot==='policy')return new File([DEMO_POLICY],'04_Politica_DEMO.txt',{type:'text/plain'});
 const {default:ExcelJS}=await import('exceljs');
 const wb=new ExcelJS.Workbook();const ws=wb.addWorksheet('Datos');
 const d=data[slot];ws.addRow(d.headers);if(!blank)d.rows.forEach(r=>ws.addRow(r));
 ws.getRow(1).font={bold:true,color:{argb:'FFFFFFFF'}};ws.getRow(1).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF217A55'}};
 ws.columns.forEach(c=>{c.width=26});ws.views=[{state:'frozen',ySplit:1}];
 const help=wb.addWorksheet('Instrucciones');help.getColumn(1).width=100;
 ['DATOS FICTICIOS · '+(blank?'Plantilla vacía':'Ejemplo para practicar'),'Subir en el botón correspondiente y seleccionar la hoja Datos.','Asignar las columnas que tienen el mismo nombre. Importar inventario primero, después precios y gastos.','No cambiar los códigos entre archivos. Valores unitarios por producto; deterioro registrado es total.','Los ceros son explícitos; una celda vacía significa información pendiente.','No usar este caso como evidencia de un cliente real.'].forEach(s=>help.addRow([s]));
 return new File([await wb.xlsx.writeBuffer()],`VNR_${slot}_${blank?'plantilla':'DEMO'}.xlsx`,{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});
}
export const FIELD_HELP={basis:'Describa qué productos incluye, la fecha de corte y cómo compara costo y VNR. Vea un texto ilustrativo en Ejemplo / Demo.',normative_reference:'Indique la norma y párrafos realmente revisados, edición y adopción local. No marque la revisión si aún está pendiente.',reversal_basis:'Si el precio se recuperó, explique la evidencia y por qué procede revertir el deterioro anterior. Ejemplo: ventas posteriores del producto B.',ledger_cost:'Saldo de inventarios antes de descontar deterioro, tomado del mayor. En la demo: 940.',ledger_impairment:'Saldo acumulado del deterioro de los productos al corte, no el gasto del año. En la demo: 65.',tolerance:'Máxima diferencia aceptada para conciliar con el mayor. En la demo: 0.01 USD.',eligible_expenses:'Solo gastos necesarios atribuibles a vender esta población.',sales_base:'Ventas comparables utilizadas para calcular el porcentaje.',allocation_basis:'Explique por qué esa base representa los costos de venta de estos productos.'};
