import {useEffect,useState} from 'react';
import {FIELDS,SLOTS,applyTable,emptyRow} from './logic.js';
import {loadContext,extractFile,processVnr,downloadVnr,saveBlob} from './api.js';
import '../of/ofWorkspace.css';
import './vnr.css';
import VnrDemo from './VnrDemo.jsx';
import {DEMO,FIELD_HELP,demoContext,demoPolicy,exampleFile} from './demo.js';
const initial={client:'',country:'Ecuador',currency:'USD',year:'',cutoff:'',visit:'',preparer:'',reviewer:'',firm:'',framework:'',edition:'',adoption:'',reuse_scope:'one',selected_tests:''};
export default function VnrTool({projectId,sharedContext,onShareContext}){
 const [tab,setTab]=useState('work'),[demoMode,setDemoMode]=useState(false);
 const [ctx,setCtx]=useState({...initial,...sharedContext}),[editing,setEditing]=useState(true),[contextReady,setContextReady]=useState(false),[refs,setRefs]=useState([]);
 const [policy,setPolicy]=useState({basis:'',normative_reference:'',selling_method:'unit',reviewed:false,evidence_reviewed:false,reversal_basis:'',eligible_expenses:'',sales_base:'',allocation_basis:''});
 const [tax,setTax]=useState({enabled:false,rate:'',reference:'',recognize_dta:false,recoverability:'',recorded_dta:'',recorded_dtl:''});
 const [sources,setSources]=useState({}),[rows,setRows]=useState([]),[ledger,setLedger]=useState({ledger_cost:'',ledger_impairment:'',tolerance:'0.01'});
 const [result,setResult]=useState(null),[active,setActive]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[confirmErase,setConfirmErase]=useState(false),[keepContext,setKeepContext]=useState(true),[kept,setKept]=useState(false);
 useEffect(()=>{let cancelled=false;setContextReady(false);if(projectId)loadContext(projectId).then(c=>{if(cancelled)return;setRefs(c.references);setCtx(prev=>({...prev,...(!sharedContext?{client:c.client,year:c.year,cutoff:c.cutoff,preparer:c.preparer}:{})}));setContextReady(true)}).catch(e=>!cancelled&&setError(e.message));return()=>{cancelled=true}},[projectId]);
 useEffect(()=>{const warn=e=>{if(rows.length||Object.keys(sources).length){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[rows.length,Object.keys(sources).length]);
 function invalidate(){setResult(null);setNotice('');setPolicy(p=>({...p,evidence_reviewed:false}));}
 function updateCtx(key,value){invalidate();setCtx(p=>({...p,[key]:value,...(key==='framework'?{edition:'',adoption:''}:{})}));setPolicy(p=>({...p,reviewed:false}));}
 async function action(fn){setError('');setBusy(true);try{await fn()}catch(e){setError(e.message)}finally{setBusy(false)}}
 const payload=()=>({context:ctx,policy,tax,rows,...ledger,evidence:Object.entries(sources).map(([slot,s])=>({slot,name:s.name,sha256:s.sha256,note:s.note}))});
 async function upload(slot,file){if(!file)return;invalidate();await action(async()=>{const extracted=await extractFile(projectId,file);setSources(s=>({...s,[slot]:{...extracted,tableIndex:0,mapping:{}}}));});}
 function mapSource(slot){try{const s=sources[slot];const next=applyTable(rows,s.tables[s.tableIndex],s.mapping,slot,s.name);invalidate();setRows(next);setNotice('Datos importados. Revise la población antes de procesar.');setError('')}catch(e){setError(e.message)}}
 async function loadDemo(framework){
  if((rows.length||Object.keys(sources).length)&&!window.confirm('Cargar la demo reemplazará la ficha, archivos y resultados de esta prueba. Descargue antes lo que necesite. ¿Continuar?'))return;
  await action(async()=>{
   const nextSources={};let nextRows=[];
   for(const [slot,,keys] of SLOTS){const file=await exampleFile(slot);const extracted=await extractFile(projectId,file);const table=extracted.tables?.[0];const mapping=Object.fromEntries(keys.map(k=>[k,table?.headers.indexOf(k)]));nextSources[slot]={...extracted,tableIndex:0,mapping};if(keys.length)nextRows=applyTable(nextRows,table,mapping,slot,file.name);}
   setCtx(demoContext(framework));setPolicy(demoPolicy(framework));setTax({enabled:false});setLedger({...DEMO.ledger});setSources(nextSources);setRows(nextRows);setResult(null);setEditing(false);setDemoMode(true);setTab('work');setNotice('DEMO cargada. Revise normativa y datos, marque ambas confirmaciones y pulse Procesar.');
  });
 }
 const field=(obj,setter,key,label,type='text')=><label key={key}>{label}<input type={type} value={obj[key]??''} onChange={e=>{invalidate();setter(p=>({...p,[key]:e.target.value}))}}/>{FIELD_HELP[key]&&<small className="vnr-help">{FIELD_HELP[key]}</small>}</label>;
 const allSources=SLOTS.every(([key])=>sources[key]);
 if(!projectId)return <p>Seleccione un proyecto antes de abrir VNR.</p>;
 return <div className="vnr-tool of-ws">
 <header className="pc-panel-h"><div><span className="pc-code">VNR</span><h2>Valor neto de realización</h2></div><span className="pc-panel-m">{result?'PROCESADO · BORRADOR':'PREPARACIÓN'}</span></header>
 <p className="vnr-note">Auditoría externa → Análisis → Inventarios. Los documentos y resultados permanecen en esta pestaña: descargue antes de salir o recargar. El servidor procesa sin conservarlos.</p>
 <div className="vnr-actions" role="tablist" aria-label="VNR"><button role="tab" aria-selected={tab==='work'} className="btn" onClick={()=>setTab('work')}>Mi prueba</button><button role="tab" aria-selected={tab==='demo'} className="btn" onClick={()=>setTab('demo')}>Ejemplo / Demo</button></div>
 {tab==='demo'&&<VnrDemo onLoad={loadDemo} busy={busy||!contextReady}/>}
 {demoMode&&<p className="vnr-note"><b>DATOS DEMO:</b> práctica con datos ficticios. Si modifica el caso, los resultados esperados de la guía pueden cambiar. Encerar antes de trabajar con datos reales.</p>}
 {error&&<p role="alert" className="vnr-error">{error}</p>}{notice&&<p role="status">{notice}</p>}
 <fieldset hidden={tab!=='work'} disabled={busy||!contextReady} className="vnr-controls">
 <section className="pc-panel"><div className="pc-panel-b"><h3>{ctx.client||'Ficha común del encargo'}</h3><p>{ctx.visit||'Visita pendiente'} · {ctx.cutoff||'Fecha pendiente'} · {ctx.framework==='full'?'NIIF completas':ctx.framework==='sme'?'NIIF para las PYMES':'Seleccione marco contable'}</p>
 <div className="vnr-actions"><button className="btn" onClick={()=>setEditing(!editing)}>Editar datos</button><button className="btn primary" disabled={editing||!allSources||!rows.length||!policy.reviewed||!policy.evidence_reviewed} onClick={()=>action(async()=>{const r=await processVnr(projectId,payload());setResult(r);setActive(6);setNotice('Procesado. Revise diferencias, ajustes y cédulas antes de concluir.');})}>Procesar</button><button className="btn" disabled={!result} onClick={()=>action(async()=>{await downloadVnr(projectId,payload(),'xlsx');setNotice('Descarga solicitada: compruebe que el Excel abre correctamente.');})}>Descargar Excel</button><button className="btn" disabled={!result} onClick={()=>action(()=>downloadVnr(projectId,payload(),'html'))}>Descargar HTML</button><button className="btn" onClick={()=>{setConfirmErase(true);setKept(false)}}>Encerar</button></div>
 {editing&&<form onSubmit={e=>{e.preventDefault();if(!ctx.framework||!ctx.firm||!ctx.visit){setError('Complete marco, firma y visita.');return;}setEditing(false);onShareContext?.(ctx.reuse_scope==='one'?null:ctx);setError('')}}><div className="vnr-grid">
 {['client','country','currency','year','cutoff','preparer','reviewer'].map((key,i)=><label key={key}>{['Cliente','País','Moneda','Ejercicio','Fecha de corte','Preparado por','Revisado por'][i]}<input required type={key==='cutoff'?'date':key==='year'?'number':'text'} value={ctx[key]} onChange={e=>updateCtx(key,e.target.value)}/></label>)}
 <label>Visita<select required value={ctx.visit} onChange={e=>updateCtx('visit',e.target.value)}><option value="">Seleccione</option><option>Preliminar</option><option>Final</option></select></label>
 <label>Firma auditora<select required value={ctx.firm} onChange={e=>updateCtx('firm',e.target.value)}><option value="">Seleccione</option><option value="audit_consulting">AuditConsulting</option><option value="partner_auditing">Partner Auditing</option></select></label>
 <label>Marco contable<select required value={ctx.framework} onChange={e=>updateCtx('framework',e.target.value)}><option value="">Seleccione expresamente</option><option value="full">NIIF completas</option><option value="sme">NIIF para las PYMES</option></select></label>
 <label>Edición aplicable{ctx.framework==='sme'?<select required value={ctx.edition} onChange={e=>updateCtx('edition',e.target.value)}><option value="">Seleccione</option><option>2015</option><option>2025</option></select>:<input required value={ctx.edition} onChange={e=>updateCtx('edition',e.target.value)}/>}</label>
 <label>Adopción local y vigencia<input required value={ctx.adoption} onChange={e=>updateCtx('adoption',e.target.value)}/></label>
 <label>Alcance de reutilización<select value={ctx.reuse_scope} onChange={e=>updateCtx('reuse_scope',e.target.value)}><option value="one">Solo esta prueba</option><option value="selected">Pruebas seleccionadas</option><option value="all">Todas las pruebas</option></select></label>
 {ctx.reuse_scope==='selected'&&<label>Pruebas seleccionadas<input required value={ctx.selected_tests} onChange={e=>updateCtx('selected_tests',e.target.value)}/></label>}
 </div><p className="vnr-note">La ficha se conserva durante esta sesión del catálogo para herramientas compatibles. El alcance también queda documentado en el Excel; no modifica encargos existentes.</p><button className="btn primary">Confirmar ficha</button></form>}</div></section>
 <section className="pc-panel"><div className="pc-panel-h"><h3>1. Norma, política y requerimiento de información</h3></div><div className="pc-panel-b">
 <ul>{refs.filter(x=>['all',ctx.framework,ctx.country].includes(x.framework)).map(x=><li key={x.url}><a href={x.url} target="_blank" rel="noreferrer">{x.title}</a></li>)}</ul>
 <p>Estas referencias orientan la revisión; no certifican cumplimiento. El motor cubre inventarios ordinarios al costo; excluye mediciones especiales de productores o intermediarios de materias primas.</p>
 <div className="vnr-grid">{field(policy,setPolicy,'basis','Política contable y alcance de población')}{field(policy,setPolicy,'normative_reference','Norma, párrafos y vigencia verificados')}{field(policy,setPolicy,'reversal_basis','Sustento de reversión, si corresponde')}</div>
 <label className="vnr-check"><input type="checkbox" checked={policy.reviewed} onChange={e=>{setResult(null);setPolicy(p=>({...p,reviewed:e.target.checked}))}}/>He verificado marco, edición, adopción local, política y procedimientos de auditoría aplicables.</label>
 </div></section>
 <section className="pc-panel"><div className="pc-panel-h"><h3>2. Subir y revisar documentos</h3><span>{Object.keys(sources).length} / 4 fuentes</span></div><div className="pc-panel-b"><p>XLSX, CSV, XML y tablas de Word permiten asignar columnas. PDF, texto e imágenes sirven de soporte: revise o transcriba los importes. ZIP: hasta 20 archivos, sin ZIP anidados. Máximo 8 MB por archivo y 2.000 ítems.</p><div className="vnr-grid">
 {SLOTS.map(([slot,label,keys])=>{const s=sources[slot],table=s?.tables?.[s.tableIndex];return <article className="vnr-source" key={slot}><h4>{label}</h4><input aria-label={'Subir '+label} type="file" accept=".xlsx,.csv,.xml,.docx,.pdf,.txt,.zip,.png,.jpg,.jpeg,.webp" onChange={e=>{upload(slot,e.target.files[0]);e.target.value=''}}/>{keys.length>0&&<button type="button" className="link" onClick={()=>saveBlob(new Blob(['\uFEFF'+keys.join(';')+'\n'],{type:'text/csv;charset=utf-8'}),'VNR_'+slot+'.csv')}>Descargar encabezados de plantilla</button>}
 {s&&<><b>{s.name}</b><p>{s.note}</p>{s.text&&<details><summary>Ver texto extraído</summary><pre>{s.text}</pre></details>}{table&&keys.length>0&&<><label>Hoja o tabla<select value={s.tableIndex} onChange={e=>setSources(prev=>({...prev,[slot]:{...s,tableIndex:Number(e.target.value),mapping:{}}}))}>{s.tables.map((t,i)=><option value={i} key={i}>{t.name} ({t.rows.length} filas)</option>)}</select></label>{keys.map(key=><label key={key}>{FIELDS.find(f=>f[0]===key)?.[1]}<select value={s.mapping[key]??''} onChange={e=>setSources(prev=>({...prev,[slot]:{...s,mapping:{...s.mapping,[key]:e.target.value}}}))}><option value="">Asignar columna</option>{table.headers.map((h,i)=><option key={i} value={i}>{h||'Columna '+(i+1)}</option>)}</select></label>)}<button type="button" className="btn" onClick={()=>mapSource(slot)}>Importar datos de esta fuente</button></>}</>}
 </article>})}</div></div></section>
 <section className="pc-panel"><div className="pc-panel-h"><h3>3. Población y parámetros de cálculo</h3></div><div className="pc-panel-b"><p>Las fuentes se vinculan por código. Los campos vacíos no se interpretan como cero. Para costos inexistentes registre cero después de revisarlos. Base fiscal solo es obligatoria si habilita diferidos.</p>
 <div className="vnr-grid"><label>Método de costos de venta<select value={policy.selling_method} onChange={e=>{invalidate();setPolicy(p=>({...p,selling_method:e.target.value}))}}><option value="unit">Costo por unidad</option><option value="ratio">Porcentaje sustentado sobre precio</option></select></label>{policy.selling_method==='ratio'&&<>{field(policy,setPolicy,'eligible_expenses','Gastos necesarios atribuibles')}{field(policy,setPolicy,'sales_base','Ventas de población comparable')}{field(policy,setPolicy,'allocation_basis','Sustento de asignación')}</>}{field(ledger,setLedger,'ledger_cost','Saldo bruto de inventarios en mayor')}{field(ledger,setLedger,'ledger_impairment','Deterioro registrado en mayor')}{field(ledger,setLedger,'tolerance','Tolerancia de conciliación')}</div>
 <div className="vnr-scroll"><table><thead><tr>{FIELDS.map(([k,l])=><th key={k}>{l}</th>)}<th>Acción</th></tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{FIELDS.map(([k,l])=><td key={k}><input aria-label={l+' fila '+(i+1)} value={row[k]??''} onChange={e=>{invalidate();setRows(old=>old.map((r,j)=>i===j?{...r,[k]:e.target.value}:r))}}/></td>)}<td><button type="button" onClick={()=>{invalidate();setRows(old=>old.filter((_,j)=>i!==j))}}>Quitar</button></td></tr>)}</tbody></table></div><button type="button" className="btn" disabled={rows.length>=2000} onClick={()=>{invalidate();setRows(old=>[...old,emptyRow()])}}>Agregar ítem manualmente</button>
 <label className="vnr-check"><input type="checkbox" checked={tax.enabled} onChange={e=>{invalidate();setTax(t=>({...t,enabled:e.target.checked}))}}/>Evaluar impuesto diferido</label>{tax.enabled&&<div className="vnr-grid">{field(tax,setTax,'rate','Tasa aplicable (decimal, p. ej. 0.25)')}{field(tax,setTax,'reference','Normativa tributaria, vigencia y base fiscal')}{field(tax,setTax,'recorded_dta','Activo diferido registrado')}{field(tax,setTax,'recorded_dtl','Pasivo diferido registrado')}<label className="vnr-check"><input type="checkbox" checked={tax.recognize_dta} onChange={e=>{invalidate();setTax(t=>({...t,recognize_dta:e.target.checked}))}}/>Reconocer activo diferido con recuperabilidad sustentada</label>{tax.recognize_dta&&field(tax,setTax,'recoverability','Evidencia de recuperabilidad')}</div>}
 <label className="vnr-check"><input type="checkbox" disabled={!allSources||!rows.length} checked={policy.evidence_reviewed} onChange={e=>{setResult(null);setPolicy(p=>({...p,evidence_reviewed:e.target.checked}))}}/>Revisé integridad, precios, costos necesarios, deterioro previo, referencias y conciliación de la población. Los datos transcritos coinciden con la evidencia.</label></div></section>
 <section className="pc-panel"><div className="pc-panel-h"><h3>4. Cédulas, diferencias y ajustes</h3></div><div className="pc-panel-b">{result?<><div className="vnr-metrics">{[['cost','Costo'],['impairment','Deterioro requerido'],['adjustment','Ajuste neto'],['reversal','Reversión']].map(([k,l])=><div key={k}><small>{l}</small><strong>{result.totals[k]}</strong></div>)}</div><p role="status">{result.controls.reconciled?'Saldos conciliados dentro de tolerancia.':'Existen diferencias con el mayor. Revise la cédula de conciliación.'}</p><div className="pc-tiles">{result.schedules.map((s,i)=><button key={s.name} className={'pc-tile'+(active===i?' on':'')} onClick={()=>setActive(i)}><span className="pc-tile-n">{i+1}</span><span>{s.title}</span></button>)}</div><h4>{result.schedules[active].title}</h4><div className="vnr-scroll"><table><thead><tr>{result.schedules[active].headers.map((h,i)=><th key={i}>{h}</th>)}</tr></thead><tbody>{result.schedules[active].rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v&&typeof v==='object'?<>{v.value}<details><summary>Fórmula</summary><code>{v.formula}</code></details></>:String(v??'')}</td>)}</tr>)}</tbody></table></div><p><b>Cómo se calcula:</b> {result.schedules[active].note}</p></>:<><p>Las doce cédulas se habilitan después de procesar la población revisada.</p><div className="pc-tiles">{['Portada del encargo','Normativa y política','Evidencia y trazabilidad','Inventario valorado','Precios de venta','Costos necesarios','Cálculo VNR','Conciliación contable','Ajustes y reversiones','Impuesto diferido','Conclusión del auditor','Control de revisión'].map((title,i)=><button disabled className="pc-tile" key={title}><span className="pc-tile-n">{i+1}</span><span>{title}<small> · Pendiente</small></span></button>)}</div></>}</div></section>
 </fieldset>{busy&&<p role="status">Procesando…</p>}
 {confirmErase&&<div className="vnr-modal" role="dialog" aria-modal="true" aria-label="Encerar herramienta"><div><h3>Encerar herramienta</h3><p>Se borrarán de esta pestaña las fuentes, importes y resultados. Los archivos descargados permanecen en su equipo.</p><label className="vnr-check"><input type="checkbox" checked={keepContext} onChange={e=>setKeepContext(e.target.checked)}/>Conservar ficha del encargo</label><label className="vnr-check"><input type="checkbox" checked={kept} onChange={e=>setKept(e.target.checked)}/>Conservo mis descargas o acepto eliminar los resultados.</label><div className="vnr-actions"><button className="btn" onClick={()=>setConfirmErase(false)}>Cancelar</button><button className="btn" disabled={!kept} onClick={()=>{setSources({});setRows([]);setResult(null);setDemoMode(false);setPolicy({basis:'',normative_reference:'',selling_method:'unit',reviewed:false,evidence_reviewed:false});setTax({enabled:false});setLedger({ledger_cost:'',ledger_impairment:'',tolerance:'0.01'});setError('');setNotice('Herramienta encerada.');setConfirmErase(false);if(!keepContext){setCtx(initial);onShareContext?.(null);setEditing(true)}}}>Confirmar encerado</button></div></div></div>}
 </div>
}
