"""Catálogo OFICIAL F-104 — Declaración Mensual del IVA (SRI Ecuador).

⚠️ FUENTE: Formulario IVA oficial publicado por el SRI Ecuador
   (FORMULARIO IVA.xlsx — hoja '1 Disenio').

Cada concepto del F-104 tiene hasta 3 casilleros relacionados:
  · Valor Bruto    (cols 401-410): venta o adquisición sin descontar NC
  · Valor Neto     (cols 411-420, 511-525): después de notas de crédito
  · Impuesto       (cols 421-430, 521-525): IVA generado / pagado

Total casilleros oficiales: 141
"""

from __future__ import annotations


F104_CASILLERO_NAMES: dict[str, str] = {
    "113": "Total comprobantes de venta emitidos — Impuesto Generado",
    "117": "Total comprobantes de venta recibidos por adquisiciones y pagos (excepto notas de venta) — Impuesto Generado",
    "119": "Total liquidaciones de compra emitidas (por pagos tarifa 0% de IVA, o por reembolsos en relación de dependencia) — Impuesto Generado",
    "203": "Decreto ejecutivo que determina el porcentaje de tarifa reducida de IVA en la prestación de servicios definidos como actividades turísticas — Impuesto",
    "401": "Ventas locales (excluye activos fijos) gravadas tarifa diferente de cero — Valor Bruto",
    "402": "Ventas de activos fijos gravadas tarifa diferente de cero — Valor Bruto",
    "403": "Ventas locales (excluye activos fijos) gravadas tarifa 0% que no dan derecho a crédito tributario — Valor Bruto",
    "404": "Ventas de activos fijos gravadas tarifa 0% que no dan derecho a crédito tributario — Valor Bruto",
    "405": "Ventas locales (excluye activos fijos) gravadas tarifa 0% que dan derecho a crédito tributario — Valor Bruto",
    "406": "Ventas de activos fijos gravadas tarifa 0% que dan derecho a crédito tributario — Valor Bruto",
    "407": "Exportaciones de bienes — Valor Bruto",
    "408": "Exportaciones de servicios y/o derechos — Valor Bruto",
    "409": "TOTAL VENTAS Y OTRAS OPERACIONES — Valor Bruto",
    "410": "Ventas locales (excluye activos fijos) gravadas tarifa diferente de cero (TARIFA VARIABLE) — Valor Bruto",
    "411": "Ventas locales (excluye activos fijos) gravadas tarifa diferente de cero — Valor Neto",
    "412": "Ventas de activos fijos gravadas tarifa diferente de cero — Valor Neto",
    "413": "Ventas locales (excluye activos fijos) gravadas tarifa 0% que no dan derecho a crédito tributario — Valor Neto",
    "414": "Ventas de activos fijos gravadas tarifa 0% que no dan derecho a crédito tributario — Valor Neto",
    "415": "Ventas locales (excluye activos fijos) gravadas tarifa 0% que dan derecho a crédito tributario — Valor Neto",
    "416": "Ventas de activos fijos gravadas tarifa 0% que dan derecho a crédito tributario — Valor Neto",
    "417": "Exportaciones de bienes — Valor Neto",
    "418": "Exportaciones de servicios y/o derechos — Valor Neto",
    "419": "TOTAL VENTAS Y OTRAS OPERACIONES — Valor Neto",
    "420": "Ventas locales (excluye activos fijos) gravadas tarifa diferente de cero (TARIFA VARIABLE) — Valor Neto",
    "421": "Ventas locales (excluye activos fijos) gravadas tarifa diferente de cero — Impuesto Generado",
    "422": "Ventas de activos fijos gravadas tarifa diferente de cero — Impuesto Generado",
    "423": "IVA generado en la diferencia entre ventas y notas de crédito con distinta tarifa (ajuste a pagar) — Impuesto Generado",
    "424": "IVA generado en la diferencia entre ventas y notas de crédito con distinta tarifa (ajuste a favor) — Impuesto Generado",
    "425": "Ventas locales (excluye activos fijos) gravadas tarifa 5% — Valor Bruto",
    "429": "TOTAL VENTAS Y OTRAS OPERACIONES — Impuesto Generado",
    "430": "Ventas locales (excluye activos fijos) gravadas tarifa diferente de cero (TARIFA VARIABLE) — Impuesto Generado",
    "431": "Transferencias de bienes y prestación de servicios no objeto o exentos de IVA — Valor Bruto",
    "434": "Ingresos por reembolso como intermediario / valores facturados por operadoras de transporte / ingresos obtenidos por parte de las sociedades de gestión colectiva como intermediarios (informativo) — Valor Bruto",
    "435": "Ventas locales (excluye activos fijos) gravadas tarifa 5% — Valor Neto",
    "441": "Transferencias de bienes y prestación de servicios no objeto o exentos de IVA — Valor Neto",
    "442": "Notas de crédito tarifa 0% por compensar próximo mes — Valor Neto",
    "443": "Notas de crédito tarifa diferente de cero por compensar próximo mes — Valor Neto",
    "444": "Ingresos por reembolso como intermediario / valores facturados por operadoras de transporte / ingresos obtenidos por parte de las sociedades de gestión colectiva como intermediarios (informativo) — Valor Neto",
    "445": "Ventas locales (excluye activos fijos) gravadas tarifa 5% — Impuesto Generado",
    "453": "Notas de crédito tarifa diferente de cero por compensar próximo mes — Impuesto Generado",
    "454": "Ingresos por reembolso como intermediario / valores facturados por operadoras de transporte / ingresos obtenidos por parte de las sociedades de gestión colectiva como intermediarios (informativo) — Impuesto Generado",
    "480": "Total transferencias gravadas tarifa diferente de cero a contado este mes — Impuesto Generado",
    "481": "Total transferencias gravadas tarifa diferente de cero a crédito este mes — Impuesto Generado",
    "482": "Total impuesto generado — Impuesto Generado",
    "483": "Impuesto a liquidar del mes anterior — Impuesto Generado",
    "484": "Impuesto a liquidar en este mes — Impuesto Generado",
    "485": "Impuesto a liquidar en el próximo mes — Impuesto Generado",
    "486": "Mes a pagar el monto de IVA diferente de cero por ventas a crédito de este mes — Impuesto Generado",
    "487": "Tamaño COPCI — Impuesto Generado",
    "499": "TOTAL IMPUESTO A LIQUIDAR EN ESTE MES — Impuesto Generado",
    "500": "Adquisiciones y pagos (excluye activos fijos) gravados tarifa diferente de cero (con derecho a crédito tributario) — Valor Bruto",
    "501": "Adquisiciones locales de activos fijos gravados tarifa diferente de cero (con derecho a crédito tributario) — Valor Bruto",
    "502": "Otras adquisiciones y pagos gravados tarifa diferente de cero (sin derecho a crédito tributario) — Valor Bruto",
    "503": "Importaciones de servicios y/o derechos gravados tarifa diferente de cero — Valor Bruto",
    "504": "Importaciones de bienes (excluye activos fijos) gravados tarifa diferente de cero — Valor Bruto",
    "505": "Importaciones de activos fijos gravados tarifa diferente de cero — Valor Bruto",
    "506": "Importaciones de bienes (incluye activos fijos) gravados tarifa 0% — Valor Bruto",
    "507": "Adquisiciones y pagos (incluye activos fijos) gravados tarifa 0% — Valor Bruto",
    "508": "Adquisiciones realizadas a contribuyentes RISE (hasta diciembre 2021), NEGOCIOS POPULARES (desde enero 2022) — Valor Bruto",
    "509": "TOTAL ADQUISICIONES Y PAGOS — Valor Bruto",
    "510": "Adquisiciones y pagos (excluye activos fijos) gravados tarifa diferente de cero (con derecho a crédito tributario) — Valor Neto",
    "511": "Adquisiciones locales de activos fijos gravados tarifa diferente de cero (con derecho a crédito tributario) — Valor Neto",
    "512": "Otras adquisiciones y pagos gravados tarifa diferente de cero (sin derecho a crédito tributario) — Valor Neto",
    "513": "Importaciones de servicios y/o derechos gravados tarifa diferente de cero — Valor Neto",
    "514": "Importaciones de bienes (excluye activos fijos) gravados tarifa diferente de cero — Valor Neto",
    "515": "Importaciones de activos fijos gravados tarifa diferente de cero — Valor Neto",
    "516": "Importaciones de bienes (incluye activos fijos) gravados tarifa 0% — Valor Neto",
    "517": "Adquisiciones y pagos (incluye activos fijos) gravados tarifa 0% — Valor Neto",
    "518": "Adquisiciones realizadas a contribuyentes RISE (hasta diciembre 2021), NEGOCIOS POPULARES (desde enero 2022) — Valor Neto",
    "519": "TOTAL ADQUISICIONES Y PAGOS — Valor Neto",
    "520": "Adquisiciones y pagos (excluye activos fijos) gravados tarifa diferente de cero (con derecho a crédito tributario) — Impuesto Generado",
    "521": "Adquisiciones locales de activos fijos gravados tarifa diferente de cero (con derecho a crédito tributario) — Impuesto Generado",
    "522": "Otras adquisiciones y pagos gravados tarifa diferente de cero (sin derecho a crédito tributario) — Impuesto Generado",
    "523": "Importaciones de servicios y/o derechos gravados tarifa diferente de cero — Impuesto Generado",
    "524": "Importaciones de bienes (excluye activos fijos) gravados tarifa diferente de cero — Impuesto Generado",
    "525": "Importaciones de activos fijos gravados tarifa diferente de cero — Impuesto Generado",
    "526": "IVA generado en la diferencia entre adquisiciones y notas de crédito con distinta tarifa (ajuste en positivo al crédito tributario) — Impuesto Generado",
    "527": "IVA generado en la diferencia entre adquisiciones y notas de crédito con distinta tarifa (ajuste en negativo al crédito tributario) — Impuesto Generado",
    "529": "TOTAL ADQUISICIONES Y PAGOS — Impuesto Generado",
    "530": "Adquisiciones y pagos (excluye activos fijos) gravados tarifa diferente de cero (con derecho a crédito tributario tarifa variable) — Valor Bruto",
    "531": "Adquisiciones no objeto de IVA — Valor Bruto",
    "532": "Adquisiciones exentas del pago de IVA — Valor Bruto",
    "533": "Adquisiciones y pagos (excluye activos fijos) gravados tarifa diferente de cero (con derecho a crédito tributario tarifa variable) — Valor Neto",
    "534": "Adquisiciones y pagos (excluye activos fijos) gravados tarifa diferente de cero (con derecho a crédito tributario tarifa variable) — Impuesto Generado",
    "535": "Pagos netos por reembolso como intermediario / valores facturados por socios a operadoras de transporte / pagos realizados por parte de las sociedades de gestión colectiva como intermediarios (informativo) — Valor Bruto",
    "540": "Adquisiciones y pagos locales (excluye activos fijos) gravados con tarifa 5% (con derecho a crédito tributario) — Valor Bruto",
    "541": "Adquisiciones no objeto de IVA — Valor Neto",
    "542": "Adquisiciones exentas del pago de IVA — Valor Neto",
    "543": "Notas de crédito tarifa 0% por compensar próximo mes — Valor Neto",
    "544": "Notas de crédito tarifa diferente de cero por compensar próximo mes — Valor Neto",
    "545": "Pagos netos por reembolso como intermediario / valores facturados por socios a operadoras de transporte / pagos realizados por parte de las sociedades de gestión colectiva como intermediarios (informativo) — Valor Neto",
    "550": "Adquisiciones y pagos locales (excluye activos fijos) gravados con tarifa 5% (con derecho a crédito tributario) — Valor Neto",
    "554": "Notas de crédito tarifa diferente de cero por compensar próximo mes — Impuesto Generado",
    "555": "Pagos netos por reembolso como intermediario / valores facturados por socios a operadoras de transporte / pagos realizados por parte de las sociedades de gestión colectiva como intermediarios (informativo) — Impuesto Generado",
    "560": "Adquisiciones y pagos locales (excluye activos fijos) gravados con tarifa 5% (con derecho a crédito tributario) — Impuesto Generado",
    "563": "Factor de proporcionalidad para crédito tributario — Impuesto Generado",
    "564": "Crédito tributario aplicable en este período (de acuerdo al factor de proporcionalidad o a su contabilidad) (520+521+534+560+523+524+525+526-527) x 563 — Impuesto Generado",
    "565": "Valor de IVA no considerado como crédito tributario por factor de proporcionalidad — Impuesto Generado",
    "601": "Impuesto causado — Impuesto Generado",
    "602": "Crédito tributario aplicable en este período — Impuesto Generado",
    "603": "(-) Compensación de IVA por ventas efectuadas con medio electrónico y/o IVA devuelto o descontado por transacciones realizadas con personas adultas mayores o personas con discapacidad — Impuesto Generado",
    "604": "(-) Compensación de IVA por ventas efectuadas en zonas afectadas - Ley de solidaridad, restitución de crédito tributario en resoluciones administrativas o sentencias judiciales de última instancia — Impuesto Generado",
    "609": "(-) Retenciones en la fuente de IVA que le han sido efectuadas en este período — Impuesto Generado",
    "610": "(+) Ajuste por IVA devuelto o descontado por adquisiciones efectuadas con medio electrónico — Impuesto Generado",
    "611": "(+) Ajuste por IVA devuelto o descontado en adquisiciones efectuadas en zonas afectadas - Ley de solidaridad — Impuesto Generado",
    "612": "(+) Ajuste por IVA devuelto e IVA rechazado (por concepto de devoluciones de IVA), ajuste de IVA por procesos de control y otros (adquisiciones en importaciones), imputables al crédito tributario — Impuesto Generado",
    "613": "(+) Ajuste por IVA devuelto e IVA rechazado, ajuste de IVA por procesos de control y otros (por concepto retenciones en la fuente de IVA), imputables al crédito tributario — Impuesto Generado",
    "614": "(+) Ajuste por IVA devuelto por otras instituciones del sector público imputable al crédito tributario en el mes — Impuesto Generado",
    "620": "SUBTOTAL A PAGAR — Impuesto Generado",
    "621": "IVA PRESUNTIVO DE SALAS DE JUEGO (BINGO MECÁNICOS) Y OTROS JUEGOS DE AZAR (Aplica para Ejercicios Anteriores al 2013), RETENCIÓN DE IVA EN VENTAS DIFERENTES PORCENTAJES (aplica para Ejercicios posteriores al 2021) — Impuesto Generado",
    "622": "(-) IVA devuelto o descontado por transacciones realizadas con personas adultas mayores o personas con discapacidad — Impuesto Generado",
    "624": "IVA pagado y no compensado, en la adquisición local o importación de bienes o servicios que se carga al gasto de Impuesto a la Renta. — Impuesto Generado",
    "625": "Ajuste del crédito tributario de Impuesto al Valor Agregado pagado en adquisiciones locales e importaciones de bienes y servicios superior a cinco (5) años — Impuesto Generado",
    "699": "TOTAL IMPUESTO A PAGAR POR PERCEPCIÓN Y RETENCIONES EFECTUADAS EN VENTAS (varios porcentajes) — Impuesto Generado",
    "700": "Importaciones de materias primas, insumos y bienes de capital que sean incorporadas en procesos productivos de bienes que se exporten — Valor Neto",
    "701": "Importaciones de materias primas, insumos y bienes de capital que sean incorporadas en procesos productivos de bienes que se exporten — Impuesto Generado",
    "702": "Proporción del ingreso neto de divisas desde el exterior al Ecuador, respecto del total de las exportaciones netas de bienes — Impuesto Generado",
    "721": "Retención del 10% — Impuesto Generado",
    "723": "Retención del 20% — Impuesto Generado",
    "725": "Retención del 30% — Impuesto Generado",
    "727": "Retención del 50% — Impuesto Generado",
    "729": "Retención del 70% — Impuesto Generado",
    "731": "Retención del 100% — Impuesto Generado",
    "799": "TOTAL IMPUESTO RETENIDO — Impuesto Generado",
    "800": "Devolución provisional de IVA mediante compensación con retenciones efectuadas — Impuesto Generado",
    "801": "TOTAL IMPUESTO A PAGAR POR RETENCIÓN — Impuesto Generado",
    "802": "Retenciones efectuadas y no pagadas sector público, universidades y escuelas politécnicas — Impuesto Generado",
    "859": "TOTAL CONSOLIDADO DE IMPUESTO AL VALOR AGREGADO — Impuesto Generado",
    "880": "Pago directo en cuenta única del tesoro nacional (uso exclusivo para instituciones y empresas del sector público autorizadas) — Impuesto Generado",
    "881": "¿Tiene derecho al pago diferido del IVA a pagar de este ejercicio fiscal conforme al Decreto 1021 del 2020 por la emergencia sanitaria en relación con el COVID-19? — Impuesto Generado",
    "882": "Cuota 1 del Impuesto al Valor Agregado del ejercicio fiscal 2020 (10%) — Impuesto Generado",
    "883": "Cuota 2 del Impuesto al Valor Agregado del ejercicio fiscal 2020 (10%) — Impuesto Generado",
    "884": "Cuota 3 del Impuesto al Valor Agregado del ejercicio fiscal 2020 (20%) — Impuesto Generado",
    "885": "Cuota 4 del Impuesto al Valor Agregado del ejercicio fiscal 2020 (20%) — Impuesto Generado",
    "886": "Cuota 5 del Impuesto al Valor Agregado del ejercicio fiscal 2020 (20%) — Impuesto Generado",
    "887": "Cuota 6 del Impuesto al Valor Agregado del ejercicio fiscal 2020 (20%) — Impuesto Generado",
    "890": "Pago previo — Impuesto Generado",
    "902": "TOTAL IMPUESTO A PAGAR — Impuesto Generado",
    "903": "Interés por mora — Impuesto Generado",
    "904": "Multa — Impuesto Generado",
    "999": "TOTAL PAGADO — Impuesto Generado",
}


def get_casillero_name(casillero: str, fallback: str = "") -> str:
    """Devuelve el nombre oficial del casillero F-104 según formulario SRI."""
    return F104_CASILLERO_NAMES.get(str(casillero).strip(), fallback)
