"""Catálogo canónico COMPLETO de casilleros del Formulario 101 — Declaración
Anual del Impuesto a la Renta Sociedades (SRI Ecuador 2025).

⚠️ VERIFICADO EMPÍRICAMENTE contra el F-101 real de PROPHAR 2025:
   PDF tiene 591 casilleros con nombre extraíble → este catálogo cubre 591+.

⚠️ REGLA SUPREMA (CLAUDE.md): verificar que TODOS los casilleros del PDF
   estén acá con su nombre oficial. NO ENTREGAR como concluido sin
   contar empíricamente PDF vs Excel generado.

Generado automáticamente desde el PDF oficial. Para regenerar:
    python scripts/extract_f101_catalog.py
"""

from __future__ import annotations


# ─────────────────────────────────────────────────────────────────────────────
# CATÁLOGO COMPLETO F-101 (591 casilleros oficiales SRI 2025)
# ─────────────────────────────────────────────────────────────────────────────
F101_CASILLERO_NAMES: dict[str, str] = {
    "003": "________ Operaciones de activo",
    "004": "Operaciones de pasivo",
    "005": "Operaciones de ingreso",
    "006": "Operaciones de egreso",
    "007": "Operaciones de regalías, servicios técnicos, administrativos, de consultoría y similares",
    "008": "Operaciones de activo",
    "009": "Operaciones de pasivo",
    "010": "Operaciones de ingreso",
    "011": "Operaciones de egreso",
    "012": "Operaciones de regalías, servicios técnicos, administrativos, de consultoría y similares",
    "013": "Operaciones de activo",
    "014": "Operaciones de pasivo",
    "015": "Operaciones de ingreso",
    "016": "Operaciones de egreso",
    "017": "Operaciones de regalías, servicios técnicos, administrativos, de consultoría y similares",
    "029": "TOTAL OPERACIONES CON PARTES RELACIONADAS",
    "038": "____ Porcentaje de reducción de tarifa aplicable en el caso de empresas existentes con nuevas inversiones productivas que genera empleo neto",
    "040": "Porcentaje de la relación entre el activo total de la entidad de menor tamaño respecto al activo total de la entidad absorbente",
    "041": "Exoneración del impuesto a la renta para las entidades del sector financiero popular y solidario resultantes de procesos de fusión de los segmentos distintos a los dos últimos",
    "043": "Exoneración del pago del saldo del impuesto a la renta del ejercicio fiscal 2015 dispuesta en la Ley Orgánica de Solidaridad y de Corresponsabilidad Ciudadana para la Reconstrucción y Reactivación ...",
    "045": "Reducción de 10% del Impuesto a la Renta del ejercicio fiscal 2019 para contribuyentes domiciliados a septiembre de 2019 cuya actividad económica principal sea la agrícola, ganadera, agroindustrial...",
    "047": "____ Porcentaje de reducción porcentual de tarifa aplicable en proyectos atención personas con discapacidad, deportivos, culturales, investigación científica, acuícola y pesquera, o desarrollo tecn...",
    "048": "Valor del beneficio en impuesto de una sociedad que dispone de un contrato de inversión con estabilidad en la tarifa de Impuesto a la Renta, de acuerdo a lo señalado en el COPCI",
    "051": "Porcentaje de reducción de tarifa superior a 10 puntos porcentuales aplicable en el caso de empresas existentes con nuevas inversiones productivas que genera empleo neto con autorización del CEPAI",
    "053": "Cuota 1 del Impuesto a la Renta del ejercicio fiscal 2019 (10%)",
    "054": "Cuota 2 del Impuesto a la Renta del ejercicio fiscal 2019 (10%)",
    "055": "Cuota 3 del Impuesto a la Renta del ejercicio fiscal 2019 (20%)",
    "056": "Cuota 4 del Impuesto a la Renta del ejercicio fiscal 2019 (20%)",
    "057": "Cuota 5 del Impuesto a la Renta del ejercicio fiscal 2019 (20%)",
    "058": "Cuota 6 del Impuesto a la Renta del ejercicio fiscal 2019 (20%)",
    "059": "Valor del beneficio en impuesto por la reducción de tres puntos porcentuales (3%) del Impuesto a la Renta para el desarrollo de nuevas inversiones",
    "060": "Valor del beneficio en impuesto por la reducción especial de la tarifa de Impuesto a la Renta por la suscripción de Contratos de Inversión",
    "061": "Porcentaje de reducción especial de la tarifa de Impuesto a la Renta por la suscripción de Contratos de Inversión",
    "063": "+) Impuesto a la Renta Causado del Régimen Simplificado para Emprendedores (RIMPE)",
    "064": "+) Valor del impuesto por el incremento de tarifa de dos puntos porcentuales (2%) por acogerse al sistema de estabilidad tributaria",
    "067": "Crédito tributario por aportes patronales a la Seguridad Social (para el ejercicio fiscal 2024 - Ley para el Alivio Financiero)",
    "069": "Valor de la donación efectuada por el contribuyente a favor de la Policía Nacional y/o Fuerzas Armadas (informativo)",
    "070": "Rebaja del Impuesto a la Renta por donaciones a favor de la Policía Nacional y/o Fuerzas Armadas - Régimen General y/o RIMPE",
    "071": "Crédito tributario por pago a cuenta sobre las utilidades no distribuidas - Artículo 39.2.1 de la LRTI",
    "094": "________ ____ Ingresos por mediciones de activos biológicos al valor razonable menos costos de venta",
    "096": "Pérdidas, costos y gastos por mediciones de activos biológicos al valor razonable menos costos de venta",
    "098": "Base de cálculo de participación a trabajadores",
    "310": "CON RELACIONADAS DEL EXTERIOR",
    "311": "Efectivo y equivalentes al efectivo",
    "312": "________ ____ ____ ____ ____ Locales",
    "313": "Del exterior",
    "314": "Deterioro acumulado del valor de cuentas y documentos por cobrar comerciales por incobrabilidad (provisiones para créditos incobrables)",
    "316": "Del exterior",
    "317": "Deterioro acumulado del valor de cuentas y documentos por cobrar comerciales por incobrabilidad (provisiones para créditos incobrables)",
    "319": "Del exterior",
    "320": "En efectivo",
    "321": "En activos diferentes del efectivo",
    "323": "Del exterior",
    "324": "Deterioro acumulado del valor de otras cuentas y documentos por cobrar por incobrabilidad (provisiones para créditos incobrables)",
    "326": "Del exterior",
    "327": "Deterioro acumulado del valor de otras cuentas y documentos por cobrar por incobrabilidad (provisiones para créditos incobrables)",
    "328": "________ ____ ____ A costo amortizado",
    "329": "Deterioro acumulado del valor de otros activos financieros corrientes medidos a costo amortizado (provisiones para créditos incobrables)",
    "330": "A valor razonable",
    "331": "Relacionadas",
    "332": "No relacionadas",
    "333": "Relacionadas",
    "334": "No relacionadas",
    "335": "Crédito tributario a favor del sujeto pasivo (ISD)",
    "336": "Crédito tributario a favor del sujeto pasivo (IVA)",
    "337": "Crédito tributario a favor del sujeto pasivo (Impuesto a la Renta)",
    "339": "________ ____ ____ Mercaderías en tránsito",
    "340": "Inventario de materia prima (no para la construcción)",
    "341": "Inventario de productos en proceso (excluyendo obras/inmuebles en construcción para la venta)",
    "342": "Inventario de prod. term. y mercad. en almacén (excluyendo obras/inmuebles terminados para la venta)",
    "343": "Inventario de suministros, herramientas, repuestos y materiales (no para la construcción)",
    "344": "Inventario de materia prima, suministros y materiales para la construcción",
    "345": "Inventario de obras/inmuebles en construcción para la venta",
    "346": "Inventario de obras/inmuebles terminados para la venta",
    "347": "Deterioro acumulado del valor de inventarios por ajuste al valor neto realizable",
    "349": "Deterioro acumulado del valor de activos no corrientes mantenidos para la venta",
    "350": "________ ____ ____ ____ A costo",
    "351": "Deterioro acumulado del valor de activos biológicos medidos a costo",
    "352": "A valor razonable menos los costos de venta",
    "354": "Deterioro acumulado del valor de activos biológicos medidos a costo",
    "355": "A valor razonable menos los costos de venta",
    "356": "Propaganda y publicidad prepagada",
    "357": "Arrendamientos operativos pagados por anticipado",
    "358": "Primas de seguro pagadas por anticipado",
    "360": "Otros Activos Corrientes",
    "361": "TOTAL ACTIVOS CORRIENTES",
    "362": "________ ____ ____ ____ Costo histórico antes de reexpresiones o revaluaciones",
    "363": "Ajuste acumulado por reexpresiones o revaluaciones",
    "364": "Costo histórico antes de reexpresiones o revaluaciones",
    "365": "Ajuste acumulado por reexpresiones o revaluaciones",
    "366": "Costo histórico antes de reexpresiones o revaluaciones",
    "367": "Ajuste acumulado por reexpresiones o revaluaciones",
    "368": "Costo histórico antes de reexpresiones o revaluaciones",
    "369": "Ajuste acumulado por reexpresiones o revaluaciones",
    "370": "Costo histórico antes de reexpresiones o revaluaciones",
    "371": "Ajuste acumulado por reexpresiones o revaluaciones",
    "372": "Construcciones en Curso y Otros Activos en Tránsito",
    "373": "Muebles y enseres",
    "374": "Equipo de Computación",
    "375": "Vehículos, Equipo de Transporte y Caminero Móvil",
    "376": "Terrenos",
    "377": "Edificios y otros inmuebles (excepto terrenos)",
    "378": "Naves, aeronaves, barcazas y similares",
    "379": "Maquinaria, equipo, instalaciones y adecuaciones",
    "380": "Equipo de computación",
    "381": "Vehículos, equipo de transporte y caminero móvil",
    "383": "Otras Propiedades, Planta y Equipo",
    "384": "Del costo histórico antes de reexpresiones o revaluaciones",
    "385": "Del ajuste acumulado por reexpresiones o revaluaciones",
    "386": "Deterioro acumulado del valor de propiedades, planta y equipo",
    "387": "________ ____ ____ Plusvalía o goodwill (derecho de llave)",
    "388": "Marcas, patentes, licencias y otros similares",
    "389": "Adecuaciones y mejoras en bienes arrendados mediante arrendamiento operativo",
    "390": "Derechos en acuerdos de concesión",
    "392": "Amortización acumulada de activos intangibles",
    "393": "Deterioro acumulado de activos intangibles",
    "394": "________ ____ ____ ____ A costo",
    "395": "A valor razonable",
    "397": "A valor razonable",
    "398": "Depreciación Acumulada de Propiedades de Inversión",
    "399": "Deterioro Acumulado del Valor de Propiedades de Inversión",
    "400": "________ ____ ____ ____ A costo",
    "401": "Depreciación acumulada de activos biológicos medidos a costo",
    "402": "Deterioro acumulado del valor de activos biológicos medidos a costo",
    "403": "A valor razonable menos los costos de venta",
    "405": "Depreciación acumulada de activos biológicos medidos a costo",
    "406": "Deterioro acumulado del valor de activos biológicos medidos a costo",
    "407": "A valor razonable menos los costos de venta",
    "408": "Tangibles",
    "409": "Intangibles",
    "410": "Depreciación / amortización acumulada de activos para exploración, evaluación y explotación",
    "411": "Deterioro acumulado del valor de activos para exploración, evaluación y explotación",
    "412": "________ ____ ____ ____ Costo",
    "413": "Ajuste acumulado por aplicación del método de la participación (valor patrimonial proporcional) (+/-)",
    "415": "Ajuste acumulado por aplicación del método de la participación (valor patrimonial proporcional) (+/-)",
    "417": "Ajuste acumulado por aplicación del método de la participación (valor patrimonial proporcional) (+/-)",
    "418": "Otros Derechos Representativos de Capital en Sociedades que no son Subsidiarias, ni Asociadas, ni Negocios Conjuntos",
    "419": "Deterioro Acumulado del Valor de Inversiones no Corrientes",
    "420": "________ ____ ____ ____ ____ Locales",
    "421": "Del exterior",
    "422": "Deterioro acumulado del valor de cuentas y documentos por cobrar comerciales por incobrabilidad (provisiones para créditos incobrables)",
    "424": "Del exterior",
    "425": "Deterioro acumulado del valor de cuentas y documentos por cobrar comerciales por incobrabilidad (provisiones para créditos incobrables)",
    "427": "Del exterior",
    "428": "Deterioro acumulado del valor de cuentas y documentos por cobrar por incobrabilidad (provisiones para créditos incobrables)",
    "430": "Del exterior",
    "431": "Deterioro acumulado del valor de cuentas y documentos por cobrar por incobrabilidad (provisiones para créditos incobrables)",
    "433": "Del exterior",
    "434": "Deterioro acumulado del valor de otras cuentas y documentos por cobrar por incobrabilidad (provisiones para créditos incobrables)",
    "435": "A costo amortizado",
    "436": "Deterioro acumulado del valor de otros activos financieros no corrientes medidos a costo amortizado (provisiones para créditos incobrables)",
    "437": "A valor razonable",
    "438": "Relacionadas",
    "439": "No Relacionadas",
    "440": "Por diferencias temporarias",
    "441": "Por pérdidas tributarias sujetas a amortización en periodos siguientes",
    "442": "Crédito tributario a favor del sujeto pasivo (ISD)",
    "443": "Crédito tributario a favor del sujeto pasivo (Impuesto a la Renta)",
    "445": "Otros Activos No Corrientes",
    "449": "TOTAL ACTIVOS NO CORRIENTES",
    "460": "________ ____ Ajustes acumulados por reexpresiones o revaluaciones de otras partidas de propiedades, planta y equipo (informativo)",
    "461": "Depreciación acumulada de los ajustes acumulados por reexpresiones o revaluaciones de otras partidas de propiedades, planta y equipo (informativo)",
    "462": "Ajustes acumulados por reexpresiones o revaluaciones de activos intangibles (informativo)",
    "463": "Amortización acumulada de los ajustes acumulados por reexpresiones o revaluaciones de activos intangibles (informativo)",
    "464": "Ajustes acumulados por reexpresiones o revaluaciones de propiedades de inversión (informativo)",
    "465": "Depreciación acumulada de los ajustes acumulados por reexpresiones o revaluaciones de propiedades de inversión (informativo)",
    "466": "Ajustes acumulados por reexpresiones o revaluaciones de activos para exploración, evaluación y explotación de recursos minerales (informativo)",
    "467": "Depreciación/amortización acumulada del ajustes acumulado por reexpresiones o revaluaciones de activos para exploración, evaluación y explotación de recursos minerales (informativo)",
    "468": "Total de las revaluaciones y otros ajustes positivos producto de valoraciones financieras excluidos del cálculo del anticipo, para todos los activos (informativo)",
    "469": "Total depreciación acumulada del ajuste acumulado por revaluaciones y otros ajustes negativos producto de valoraciones financieras excluidos del cálculo del anticipo, para todos los activos (inform...",
    "470": "Total costo de terrenos en los que se desarrollan actividades agropecuarias (excluyendo sus revaluaciones o reexpresiones) (informativo)",
    "471": "Total deterioro acumulado del costo de terrenos en los que se desarrollan actividades agropecuarias (informativo)",
    "472": "Total costo de terrenos en los que se desarrollan proyectos inmobiliarios para la vivienda de interés social (excluyendo sus revaluaciones o reexpresiones) (informativo)",
    "473": "Total deterioro acumulado del costo de terrenos en los que se desarrollan proyectos inmobiliarios para la vivienda de interés social (informativo)",
    "474": "Total de intereses implícitos no devengados (futuros ingresos financieros en el estado de resultados) por acuerdos que constituyen efectivamente una transacción financiera o cobro diferido (informa...",
    "475": "Activos (fideicomitidos y generados) en fideicomisos mercantiles o encargos fiduciarios donde el contribuyente es constituyente o aportante (informativo)",
    "476": "Activos adquiridos por el valor de las utilidades reinvertidas generadas en el período anterior al declarado (informativo)",
    "490": "Derechos de uso por activos arrendados",
    "491": "Amortización acumulada de derechos de uso por activos arrendados",
    "499": "TOTAL DEL ACTIVO",
    "511": "________ ____ ____ ____ ____ Locales",
    "512": "Del exterior",
    "514": "Del exterior",
    "516": "Del exterior",
    "517": "En efectivo",
    "518": "En activos diferentes del efectivo",
    "520": "Del exterior",
    "522": "Del exterior",
    "523": "________ ____ ____ ____ Locales",
    "524": "Del exterior",
    "526": "Del exterior",
    "527": "Crédito A Mutuo",
    "528": "Porción Corriente de Obligaciones Emitidas",
    "529": "A costo amortizado",
    "530": "A valor razonable",
    "531": "Porción Corriente de Arrendamientos Financieros Por Pagar",
    "532": "Impuesto A La Renta Por Pagar Del Ejercicio",
    "533": "Participación trabajadores por pagar del ejercicio",
    "534": "Obligaciones con el IESS",
    "535": "Jubilación Patronal",
    "536": "Otros Pasivos Corrientes Por Beneficios a Empleados",
    "537": "________ ____ ____ Por garantías",
    "538": "Por desmantelamiento",
    "539": "Por contratos onerosos",
    "540": "Por reestructuraciones de negocios",
    "541": "Por reembolsos a clientes",
    "542": "Por litigios",
    "543": "Por pasivos contingentes asumidos en una combinación de negocios",
    "545": "Anticipos de clientes",
    "546": "Subvenciones del Gobierno",
    "548": "Transferencias casa matriz y sucursales (del exterior)",
    "550": "________ TOTAL PASIVOS CORRIENTES",
    "553": "________ ____ ____ ____ ____ Locales",
    "554": "Del exterior",
    "556": "Del exterior",
    "558": "Del exterior",
    "560": "Del exterior",
    "562": "Del exterior",
    "563": "________ ____ ____ ____ Locales",
    "564": "Del exterior",
    "566": "Del exterior",
    "567": "Crédito a mutuo",
    "568": "Porción no corriente de obligaciones emitidas",
    "569": "A costo amortizado",
    "570": "A valor razonable",
    "571": "Porción no corriente de arrendamientos financieros por pagar",
    "572": "Pasivo por Impuesto a la Renta diferido",
    "573": "Jubilación Patronal",
    "574": "Desahucio",
    "575": "Otros Pasivos No Corrientes Por Beneficios A Empleados",
    "576": "________ ____ ____ Por garantías",
    "577": "Por desmantelamiento",
    "578": "Por contratos onerosos",
    "579": "Por reestructuraciones de negocios",
    "580": "Por reembolsos a clientes",
    "581": "Por litigios",
    "582": "Por pasivos contingentes asumidos en una combinación de negocios",
    "584": "Anticipos de clientes",
    "585": "Subvenciones del gobierno",
    "587": "Transferencias casa matriz y sucursales (del exterior)",
    "589": "TOTAL PASIVOS NO CORRIENTES",
    "591": "Total de intereses implícitos no devengados (futuros gastos financieros en el estado de resultados) por acuerdos que constituyen efectivamente una transacción financiera o pago diferido (Informativo)",
    "592": "Pasivos incurridos en fideicomisos mercantiles o encargos fiduciarios donde el contribuyente es constituyente o aportante (Informativo)",
    "593": "Pasivo corriente por arrendamiento",
    "594": "Pasivo no corriente por arrendamiento",
    "599": "TOTAL DEL PASIVO",
    "601": "Capital suscrito y/o asignado",
    "602": "Capital suscrito no pagado, acciones en tesorería",
    "603": "Aportes de socios, accionistas, partícipes, fundadores, constituyentes, beneficiarios u otros titulares de derechos representativos de capital para futura capitalización",
    "604": "________ ____ Reserva legal",
    "605": "Reserva facultativa",
    "607": "________ ____ Reserva de capital",
    "608": "Reserva por donaciones",
    "609": "Reserva por valuación (procedente de la aplicación de normas ecuatorianas de contabilidad - NEC)",
    "610": "Superávit por revaluación de inversiones (procedente de la aplicación de normas ecuatorianas de contabilidad - NEC)",
    "611": "Utilidades acumuladas de ejercicios anteriores",
    "612": "Pérdidas acumuladas de ejercicios anteriores",
    "613": "Excedente / pérdida del ejercicio anterior (con socios) (+/-)",
    "614": "Resultados acumulados por adopción por primera vez de las NIIF (+/-)",
    "615": "Utilidad del ejercicio",
    "616": "Pérdida del ejercicio",
    "617": "Excedente / pérdida del ejercicio económico (con socios) (+/-)",
    "618": "________ ____ ____ Propiedades, Planta y Equipo",
    "619": "Activos intangibles",
    "626": "Dividendos declarados (distribuidos) a favor de titulares de derechos representativos de capital en el ejercicio fiscal (Informativo)",
    "627": "Dividendos pagados (liquidados) a titulares de derechos representativos de capital en el ejercicio fiscal (Informativo)",
    "698": "TOTAL DEL PATRIMONIO",
    "699": "TOTAL PASIVO Y PATRIMONIO",
    "800": "Saldo del anticipo pendiente de pago (traslade campo 876 declaración período anterior - vigente hasta el ejercicio fiscal 2018)",
    "801": "UTILIDAD DEL EJERCICIO",
    "802": "PÉRDIDA DEL EJERCICIO",
    "803": "________ ____ (-) Participación a trabajadores",
    "804": "Dividendos exentos y efectos por método de participación (valor patrimonial proporcional) campos: 6024 + 6026 + 6132",
    "805": "Otras rentas exentas e ingresos no objeto de Impuesto a la Renta (no relacionadas a actividades con Impuesto a la Renta Único)",
    "806": "+) Gastos no deducibles locales",
    "807": "+) Gastos no deducibles del exterior",
    "808": "+) Gastos incurridos para generar ingresos exentos y gastos atribuidos a ingresos no objeto de Impuesto a la Renta",
    "809": "+) Participación trabajadores atribuible a ingresos exentos y no objeto de impuesto a la renta Fórmula: {(804x15%) + [(805-808)x15%]}",
    "810": "Deducciones adicionales",
    "811": "+) Ajuste por precios de transferencia",
    "812": "Ingresos sujetos a Impuesto a la Renta Único",
    "813": "+) Costos y gastos incurridos para generar ingresos sujetos a Impuesto a la Renta Único",
    "814": "Por valor neto realizable de inventarios",
    "816": "Por provisiones para desahucio pensiones jubilares patronales",
    "818": "Por costos estimados de desmantelamiento",
    "820": "Por deterioros del valor de propiedades, planta y equipo",
    "822": "Por provisiones (diferentes de cuentas incobrables, desmantelamiento, desahucio y jubilación patronal)",
    "828": "________ ____ ____ Ingresos",
    "830": "Pérdidas, costos y gastos",
    "833": "Amortización pérdidas tributarias de años anteriores",
    "834": "Por otras diferencias temporarias permitidas por la normativa tributaria (+/-)",
    "836": "Utilidad gravable",
    "837": "Pérdida sujeta a amortización en períodos siguientes",
    "839": "Porcentaje de la composición societaria y beneficiarios finales no informada (dentro de los plazos establecidos)",
    "840": "Porcentaje de la composición societaria correspondiente a paraísos fiscales y beneficiario final en Ecuador al 31 de diciembre del ejercicio declarado que sí ha sido informada",
    "842": "________ ____ ____ Utilidad gravable",
    "844": "____ ____ Pérdida sujeta a amortización en períodos siguientes",
    "846": "____ Utilidad a reinvertir y capitalizar (sujeta legalmente a reducción de la tarifa)",
    "848": "____ Saldo utilidad gravable",
    "850": "Total impuesto causado",
    "851": "Anticipo determinado correspondiente al ejercicio fiscal declarado (hasta el ejercicio fiscal 2018) - Anticipo pagado (para el ejercicio fiscal 2019)",
    "852": "=) Rebaja del saldo del anticipo - decreto ejecutivo no. 210 (aplica para únicamente para el ejercicio 2017)",
    "853": "=) Anticipo reducido correspondiente al ejercicio fiscal declarado (aplica para únicamente para el ejercicio 2017) (851-852)",
    "854": "=) Impuesto a la Renta causado mayor al anticipo reducido (850-853)",
    "855": "=) Crédito tributario generado por anticipo (en régimen general aplica para ejercicios anteriores al 2010)",
    "856": "+) Saldo del anticipo pendiente de pago (vigente hasta el ejercicio fiscal 2018)",
    "857": "Retenciones en la fuente que le realizaron en el ejercicio fiscal (excepto retenciones aplicables al régimen de microempresas y de las actividades sujetas al Impuesto a la Renta Único)",
    "858": "Retenciones por dividendos anticipados",
    "859": "Retenciones o impuesto pagado por ingresos provenientes del exterior con derecho a crédito tributario",
    "860": "Anticipo de impuesto a la renta pagado por espectáculos públicos",
    "861": "Crédito tributario de años anteriores",
    "862": "Generado en el ejercicio fiscal declarado",
    "863": "Generado en ejercicios fiscales anteriores",
    "865": "Subtotal impuesto a pagar",
    "866": "Subtotal saldo a favor",
    "867": "+) Impuesto a la Renta Único",
    "868": "Crédito tributario para la liquidación del Impuesto a la Renta Único",
    "869": "Impuesto a la Renta a pagar",
    "870": "Saldo a favor contribuyente",
    "871": "________ ____ ____ Anticipo calculado próximo año (Informativo a partir del ejercicio fiscal 2019)",
    "872": "Exoneraciones y rebajas al anticipo",
    "873": "+) Otros conceptos",
    "879": "Anticipo determinado próximo año",
    "880": "+/-) Propiedades, planta y equipo",
    "881": "+/-) Activos intangibles",
    "882": "+/-) Otros",
    "883": "+/-) Ganancias y pérdidas por inversiones en instrumentos de patrimonio medidos a valor razonable con cambios en otro resultado integral",
    "884": "+/-) Ganancias y pérdidas por la conversión de estados financieros de un negocio en el extranjero",
    "885": "+/-) Ganancias y pérdidas actuariales",
    "886": "+/-) La parte efectiva de las ganancias y pérdidas de los instrumentos de cobertura en una cobertura de flujos de efectivo",
    "887": "+/-) Otros",
    "888": "Gasto (ingreso) por impuesto a la renta corriente (+/-)",
    "889": "Gasto (ingreso) por impuesto a la renta diferido (+/-)",
    "890": "Pago previo (Informativo)",
    "891": "Intereses por el anticipo de Impuesto a la Renta pagado voluntariamente",
    "892": "Anticipo de Impuesto a la Renta pagado voluntariamente",
    "893": "Anticipo de Impuesto a la Renta pagado obligatoriamente por el Decreto 1137 (para el ejercicio fiscal 2020)",
    "894": "Crédito tributario por impuesto a la utilidad en la compraventa de predios urbanos y plusvalía pagados a Municipios (para actividades de urbanización, lotización y otras similares)",
    "895": "Autoretenciones efectuadas sobre los ingresos gravados por aplicación del Artículo 92.1 del RALRTI (aplica a IFIs, empresas de telefonía móvil y con contratos para la exploración y explotación de h...",
    "896": "Autoretenciones de las sociedades Grandes Contribuyentes por aplicación del Artículo 45 de la LRTI",
    "897": "________ ____ Interés",
    "898": "Impuesto",
    "902": "TOTAL IMPUESTO A PAGAR",
    "903": "Interés por mora",
    "999": "TOTAL PAGADO",
    "1005": "TOTAL INGRESOS DE ACTIVIDADES ORDINARIAS",
    "1045": "TOTAL INGRESOS NO OPERACIONALES",
    "1100": "Ingresos sujetos al Impuesto a la Renta Único para las actividades del Sector Bananero (producción y venta local)",
    "1101": "Ingresos sujetos al Impuesto a la Renta Único para las actividades del Sector Bananero (exportación)",
    "1102": "Costos y gastos incurridos para generar ingresos sujetos a Impuesto a la Renta Único para las actividades del Sector Bananero (producción y venta local)",
    "1103": "Costos y gastos incurridos para generar ingresos sujetos a Impuesto a la Renta Único para las actividades del Sector Bananero (exportación)",
    "1104": "Ingresos sujetos al Impuesto a la Renta Único para las actividades Agropecuarias (producción y comercialización local)",
    "1105": "Ingresos sujetos al Impuesto a la Renta Único para las actividades Agropecuarias (exportación)",
    "1106": "Costos y gastos incurridos para generar ingresos sujetos a Impuesto a la Renta Único para las actividades Agropecuarias (producción y comercialización local)",
    "1107": "Costos y gastos incurridos para generar ingresos sujetos a Impuesto a la Renta Único para las actividades Agropecuarias (exportación)",
    "1108": "Ingresos sujetos al Impuesto a la Renta Único para las actividades de producción y cultivo de Palma Aceitera",
    "1109": "Costos y gastos incurridos para generar ingresos sujetos a Impuesto a la Renta Único para las actividades de producción y cultivo de Palma Aceitera",
    "1110": "Ingresos (utilidad) sujetos al Impuesto a la Renta Único en la enajenación de derechos representativos de capital",
    "1111": "Costos y gastos incurridos para generar ingresos sujetos a Impuesto a la Renta Único en la enajenación de derechos representativos de capital",
    "1112": "Ingresos sujetos al Impuesto a la Renta del Régimen Impositivo de Microempresas o del Régimen Simplificado para Emprendedores (RIMPE)",
    "1113": "+) Costos y gastos incurridos para generar ingresos sujetos al Impuesto a la Renta del Régimen Impositivo de Microempresas o del Régimen Simplificado para Emprendedores (RIMPE)",
    "1114": "Por la diferencia entre los cánones de arrendamiento pactados y los cargos que deban registrarse por el reconocimiento de un activo por derecho de uso",
    "1116": "Ingresos provenientes de contratos de construcción",
    "1118": "Pérdidas, costos y gastos provenientes de contratos de construcción",
    "1120": "Ganancias que surjan de la medición de activos no corrientes mantenidos para la venta",
    "1122": "Pérdidas que surjan de la medición de activos no corrientes mantenidos para la venta",
    "1124": "+) Impuesto a la Renta Único calculado para las actividades del Sector Bananero (producción y venta local)",
    "1125": "+) Impuesto a la Renta Único calculado para las actividades del Sector Bananero (exportación)",
    "1126": "Impuesto a la Renta Único calculado para las actividades del Sector Bananero (componente exportación)",
    "1127": "Impuesto a la Renta Único calculado para las actividades del Sector Bananero (componente producción propia)",
    "1128": "Exoneración del Impuesto a la Renta Único para las actividades del Sector Bananero por nuevas inversiones",
    "1129": "Exoneración del Impuesto a la Renta Único para las actividades del Sector Bananero por creación de nuevas sociedades",
    "1130": "Exoneración del Impuesto a la Renta Único para las actividades del Sector Bananero por otros conceptos",
    "1131": "Retenciones en la fuente por Impuesto a la Renta Único para las actividades del Sector Bananero (producción y venta local)",
    "1132": "Retenciones en la fuente por Impuesto a la Renta Único para las actividades del Sector Bananero (exportación)",
    "1133": "=) Crédito tributario por Impuesto a la Renta Único para las actividades del Sector Bananero (informativo)",
    "1134": "=) Impuesto a la Renta Único a pagar por actividades del Sector Bananero",
    "1135": "+) Impuesto a la Renta Único calculado para las actividades Agropecuarias (producción y comercialización local)",
    "1136": "+) Impuesto a la Renta Único calculado para las actividades Agropecuarias (exportación)",
    "1137": "Exoneración del Impuesto a la Renta Único para las actividades Agropecuarias por nuevas inversiones",
    "1138": "Exoneración del Impuesto a la Renta Único para las actividades Agropecuarias por creación de nuevas sociedades",
    "1139": "Exoneración del Impuesto a la Renta Único para las actividades Agropecuarias por otros conceptos",
    "1140": "Retenciones en la fuente por Impuesto a la Renta Único para las actividades Agropecuarias (producción y comercialización local)",
    "1141": "Retenciones en la fuente por Impuesto a la Renta Único para las actividades Agropecuarias (exportación)",
    "1142": "Retenciones en la fuente de otros regímenes aplicables al Impuesto a la Renta Único para actividades Agropecuarias (exportación)",
    "1143": "=) Crédito tributario por Impuesto a la Renta Único para las actividades Agropecuarias (informativo)",
    "1144": "=) Impuesto a la Renta Único a pagar por actividades Agropecuarias",
    "1145": "+) Impuesto a la Renta Único para las actividades de producción y cultivo de Palma Aceitera",
    "1146": "Crédito tributario para la liquidación del Impuesto a la Renta Único para las actividades de producción y cultivo de Palma Aceitera",
    "1147": "+) Impuesto a la Renta Único en la enajenación de derechos representativos de capital",
    "1148": "Crédito tributario para la liquidación del Impuesto a la Renta Único en la enajenación de derechos representativos de capital",
    "1149": "Crédito tributario del Régimen Impositivo para Microempresas",
    "1150": "Ajuste por precios de transferencia para los ingresos sujetos al Impuesto a la Renta Único para las actividades del Sector Bananero (informativo)",
    "1151": "Propiedades, planta y equipo asociados a las reservas mineras",
    "1152": "Depreciación acumulada propiedades, planta y equipo asociados a las reservas mineras",
    "1153": "Deterioro acumulado propiedades, planta y equipo asociados a las reservas mineras",
    "1154": "Inversiones realizadas en las fases de prospección, exploración inicial, exploración avanzada y evaluación económica del yacimiento",
    "1155": "Inversiones de exploración complementaria durante la fase de explotación",
    "1156": "Inversiones de preparación y desarrollo del yacimiento",
    "1157": "Amortización acumulada de inversiones realizadas en las fases de prospección, exploración inicial, exploración avanzada y evaluación económica del yacimiento",
    "1158": "Amortización acumulada de inversiones de exploración complementaria durante la fase de explotación",
    "1159": "Amortización acumulada de inversiones de preparación y desarrollo del yacimiento",
    "1160": "Ingresos consolidados sujetos al IRU para las actividades agropecuarias del contribuyente y sus partes relacionadas por la producción, comercialización local y exportación según el Art. 27.1 de la ...",
    "1161": "Ingresos sujetos al Impuesto a la Renta Único de los operadores de pronósticos deportivos",
    "1162": "Costos y gastos incurridos para generar ingresos sujetos al Impuesto a la Renta Único de los operadores de pronósticos deportivos (según artículo 35.5 de la LRTI, premios pagados)",
    "1163": "Ingresos sujetos al Impuesto a la Renta Único de los beneficiarios de premios obtenidos por pronósticos deportivos",
    "1164": "Costos y gastos incurridos para generar ingresos sujetos al Impuesto a la Renta Único de los beneficiarios de premios obtenidos por pronósticos deportivos",
    "1165": "+) Pérdidas en concesiones mineras otorgadas a un mismo titular (sociedades sujetas al Régimen Tributario de las empresas mineras)",
    "1166": "Por deterioro de los activos financieros correspondientes a créditos incobrables (para entidades no financieras)",
    "1168": "Por la diferencia entre la depreciación financiera de propiedad, planta y equipo y los límites de deducibilidad de dicha depreciación",
    "1170": "+) Ajuste por Impuesto a la Renta Único de las actividades agropecuarias por ingresos consolidados del contribuyente y sus partes relacionadas (Art. 27.1 de la LRTI)",
    "1171": "Valor pagado del Impuesto a la Renta Único de las actividades agropecuarias que le corresponda por ingresos consolidados del contribuyente y sus partes relacionadas (Art. 27.1 de la LRTI)",
    "1172": "+) Impuesto a la Renta Único a los operadores de pronósticos deportivos (informativo)",
    "1173": "Crédito tributario para la liquidación del Impuesto a la Renta Único a los operadores de pronósticos deportivos",
    "1174": "+) Impuesto a la Renta Único a los beneficiarios de premios obtenidos por pronósticos deportivos",
    "1175": "Retenciones en la fuente por Impuesto a la Renta Único a los beneficiarios de premios obtenidos por pronósticos deportivos",
    "1176": "Rebaja del Impuesto a la Renta Único para las actividades del Sector Bananero por donaciones a favor de la Policía Nacional y/o Fuerzas Armadas",
    "1177": "Rebaja del Impuesto a la Renta Único para las actividades Agropecuarias por donaciones a favor de la Policía Nacional y/o Fuerzas Armadas",
    "1178": "Crédito tributario del Impuesto a la Renta Único para las actividades del Sector Bananero por pago a cuenta sobre las utilidades no distribuidas - Artículo 39.2.1 de la LRTI",
    "1179": "Crédito tributario del Impuesto a la Renta Único para las actividades Agropecuarias por pago a cuenta sobre las utilidades no distribuidas - Artículo 39.2.1 de la LRTI",
    "6001": "________ ____ ____ Gravadas con tarifa diferente de 0% de IVA",
    "6003": "Gravadas con tarifa 0% de iva o exentas de IVA",
    "6005": "Gravadas con tarifa diferente de 0% de IVA",
    "6007": "Gravadas con tarifa 0% de iva o exentas de IVA",
    "6009": "De bienes",
    "6011": "De servicios",
    "6013": "Por prestación de servicios de construcción",
    "6015": "Obtenidos bajo la modalidad de comisiones o similares (relaciones de agencia)",
    "6017": "Obtenidos por arrendamientos operativos",
    "6019": "________ ____ ____ RELACIONADAS",
    "6021": "NO RELACIONADAS",
    "6023": "Procedentes de sociedades residentes o establecidas en Ecuador",
    "6025": "Procedentes de sociedades no residentes ni establecidas en Ecuador",
    "6027": "Ganancias netas por mediciones de activos biológicos a valor razonable menos costos de venta",
    "6029": "Ganancias netas por medición de propiedades de inversión a valor razonable",
    "6031": "Ganancias netas por medición de instrumentos financieros a valor razonable",
    "6033": "Ganancias netas por diferencias de cambios",
    "6035": "Utilidad en venta de propiedades, planta y equipo",
    "6037": "Utilidad en la enajenación de derechos representativos de capital",
    "6039": "Ingresos devengados por subvenciones del gobierno y otras ayudas gubernamentales",
    "6041": "________ ____ ____ De activos financieros (reversión de provisiones para créditos incobrables)",
    "6043": "De inventarios",
    "6045": "De activos no corrientes mantenidos para la venta",
    "6047": "De activos biológicos",
    "6049": "De propiedades, planta y equipo",
    "6051": "De activos intangibles",
    "6053": "De propiedades de inversión",
    "6055": "De activos de exploración, evaluación y explotación de recursos minerales",
    "6057": "De inversiones no corrientes",
    "6061": "________ ____ ____ Por garantías",
    "6063": "Por desmantelamientos",
    "6065": "Por contratos onerosos",
    "6067": "Por reestructuraciones de negocios",
    "6069": "Por reembolsos a clientes",
    "6071": "Por litigios",
    "6073": "Por pasivos contingentes asumidos en una combinación de negocios",
    "6077": "Jubilación patronal y desahucio",
    "6081": "De recursos públicos",
    "6083": "De otras locales",
    "6085": "Del exterior",
    "6087": "Por lucro cesante",
    "6091": "Provenientes del exterior",
    "6095": "________ ____ ____ ____ ____ Local",
    "6097": "Del exterior",
    "6101": "Del exterior",
    "6105": "Del exterior",
    "6109": "Del exterior",
    "6113": "Del exterior",
    "6117": "Del exterior",
    "6121": "Del exterior",
    "6125": "Del exterior",
    "6127": "Intereses implícitos devengados por acuerdos que constituyen efectivamente una transacción financiera o cobro diferido",
    "6131": "Ganancias por medición de inversiones en asociadas y negocios conjuntos al método de la participación (valor patrimonial proporcional)",
    "6135": "________ Ganancias netas procedentes de actividades discontinuadas",
    "6140": "Ventas netas de propiedades, planta y equipo (Informativo)",
    "6141": "Ingresos por reembolso como intermediario / monto total facturado por operadoras de transporte con puntos de emisión asignados a socios (Informativo)",
    "6142": "Dividendos declarados (distribuidos) a favor del contribuyente en el ejercicio fiscal (Informativo)",
    "6143": "Dividendos cobrados (recaudados) por el contribuyente en el ejercicio fiscal (Informativo)",
    "6144": "________ Utilidades (Informativo)",
    "6145": "Excedentes (Informativo)",
    "6146": "Correspondiente a los valores brutos de los bienes o servicios vendidos bajo la modalidad de comisiones o similares (Informativo)",
    "6147": "bienes o servicios vendidos bajo la modalidad de comisiones o similares (Informativo)",
    "6148": "Ingresos generados por compañías de transporte internacional por sus operaciones habituales de transporte (Informativo)",
    "6149": "Ingresos generados en fideicomisos mercantiles o encargos fiduciarios donde el contribuyente es constituyente o aportante (Informativo)",
    "6150": "Ingresos no objeto de impuesto a la renta",
    "6151": "Ingresos obtenidos en dinero electrónico (Informativo)",
    "6152": "Ingresos brutos totales según contabilidad",
    "6241": "Prestación de servicios de custodia de activos financieros",
    "6251": "Prestación de servicios de operaciones de inversión en nombre de terceros",
    "6261": "Por actividades de inversión, reinversión o de negociación de activos financieros (si la sociedad es administrada por una Institución Financiera)",
    "6999": "TOTAL INGRESOS",
    "7001": "________ ____ Inventario inicial de bienes no producidos por el sujeto pasivo",
    "7004": "Compras netas locales de bienes no producidos por el sujeto pasivo",
    "7007": "Importaciones de bienes no producidos por el sujeto pasivo",
    "7010": "Inventario final de bienes no producidos por el sujeto pasivo",
    "7013": "Inventario inicial de materia prima",
    "7016": "Compras netas locales de materia prima",
    "7019": "Importaciones de materia prima",
    "7022": "Inventario final de materia prima",
    "7025": "Inventario inicial de productos en proceso",
    "7028": "Inventario final de productos en proceso",
    "7031": "Inventario inicial productos terminados",
    "7034": "Inventario final de productos terminados",
    "7037": "+ / -) Ajustes (+/-)",
    "7040": "________ ____ Sueldos, salarios y demás remuneraciones que constituyen materia gravada del iess",
    "7043": "Beneficios sociales, indemnizaciones y otras remuneraciones que no constituyen materia gravada del IESS",
    "7046": "Aporte a la seguridad social (incluye fondo de reserva)",
    "7049": "Honorarios profesionales y dietas",
    "7052": "Honorarios y otros pagos a no residentes por servicios ocasionales",
    "7055": "Jubilación patronal",
    "7058": "Desahucio",
    "7064": "________ ____ ____ Acelerada",
    "7067": "No acelerada",
    "7070": "Del costo histórico de propiedades de inversión",
    "7073": "Del costo histórico de activos para exploración, evaluación y explotación de recursos minerales",
    "7076": "Propiedades, planta y equipo",
    "7079": "Propiedades de inversión",
    "7082": "Activos para exploración, evaluación y explotación de recursos minerales",
    "7088": "De Activos Biológicos",
    "7091": "Otras depreciaciones",
    "7094": "Del costo histórico de Activos Intangibles",
    "7097": "Del costo histórico de activos para la exploración evaluación y explotación de recursos minerales",
    "7100": "________ ____ ____ Activos intangibles",
    "7103": "Activos para la exploración. Evaluación y explotación de recursos minerales",
    "7109": "Otras amortizaciones",
    "7113": "________ ____ De activos financieros (de provisiones para créditos incobrables)",
    "7115": "De inventarios",
    "7119": "De activos no corrientes mantenidos para la venta",
    "7122": "De activos biológicos",
    "7124": "De propiedades, planta y equipo",
    "7127": "De activos intangibles",
    "7131": "De propiedades de inversión",
    "7134": "De activos de exploración, evaluación y explotación de recursos minerales",
    "7137": "De inversiones no corrientes",
    "7142": "________ ____ Por garantías",
    "7145": "Por desmantelamientos",
    "7149": "Por contratos onerosos",
    "7152": "Por reestructuraciones de negocios",
    "7155": "Por reembolsos a clientes",
    "7158": "Por litigios",
    "7160": "Por pasivos contingentes asumidos en una combinación de negocios",
    "7166": "Relacionadas",
    "7169": "No relacionadas",
    "7173": "Promoción y publicidad",
    "7176": "Transporte",
    "7178": "Consumo de combustibles y lubricantes",
    "7182": "Gastos de viaje",
    "7185": "Gastos de gestión",
    "7188": "Arrendamientos operativos",
    "7190": "Suministros, herramientas, materiales y repuestos",
    "7194": "Pérdida en la enajenación de derechos representativos de capital",
    "7196": "Mantenimiento y reparaciones",
    "7202": "Seguros y reaseguros (primas y cesiones)",
    "7205": "Gastos indirectos asignados desde el exterior por partes relacionadas",
    "7208": "Impuestos, contribuciones y otros",
    "7211": "________ ____ ____ ____ Local",
    "7214": "Del exterior",
    "7220": "Del exterior",
    "7226": "Del exterior",
    "7232": "Del exterior",
    "7235": "Instalación, organización y similares",
    "7238": "IVA que se carga al costo o gasto",
    "7241": "Servicios públicos",
    "7245": "Pérdidas por siniestros",
    "7251": "____ ____ ____ ____ ____ ____ Local",
    "7254": "Del exterior",
    "7260": "Del exterior",
    "7266": "Del exterior",
    "7272": "Del exterior",
    "7278": "Del exterior",
    "7284": "Del exterior",
    "7290": "Del exterior",
    "7296": "Del exterior",
    "7299": "Reversiones del descuento de provisiones que fueron reconocidas a su valor presente",
    "7302": "Intereses implícitos devengados por acuerdos que constituyen efectivamente una transacción financiera o pago diferido",
    "7308": "Pérdidas por medición de inversiones en asociadas y negocios conjuntos al método de la participación (valor patrimonial proporcional)",
    "7314": "Pérdidas netas procedentes de actividades disconitnuadas",
    "7321": "Del exterior",
    "7327": "Del exterior",
    "7653": "De derechos de uso por activos arrendados",
    "7792": "INTERESES DEL PASIVO POR ARRENDAMIENTO",
    "7901": "Baja de inventario (Informativo)",
    "7902": "Pago por reembolso como reembolsante / monto total facturado por socios por puntos de emisión a operadoras de transporte (Informativo)",
    "7903": "Pago por reembolso como intermediario (Informativo)",
    "7905": "Costos y gastos generados en fideicomisos mercantiles o encargos fiduciarios donde el contribuyente es constituyente o aportante (Informativo)",
    "7906": "Gastos atribuidos a ingresos no objeto de impuesto a la renta",
    "7907": "Costos y gastos realizados con dinero electrónico (Informativo)",
    "7908": "Incentivos ley de solidaridad (inversiones nuevas, exoneración para IFIS y compensación por el exceso de las contribuciones solidarias)",
    "7991": "TOTAL COSTOS OPERACIONALES",
    "7992": "TOTAL GASTOS",
    "7999": "TOTAL COSTOS Y GASTOS",
}


def get_casillero_name(casillero: str, fallback: str = "") -> str:
    """Devuelve el nombre oficial del casillero F-101."""
    return F101_CASILLERO_NAMES.get(str(casillero).strip(), fallback)
