"""Catálogo OFICIAL F-103 — Retenciones en la Fuente del Impuesto a la Renta.

⚠️ FUENTE: Tabla 1 de la "Guía del Contribuyente Llenado del XML y JSON
   Retenciones en la Fuente" publicada por el SRI Ecuador.

Total casilleros oficiales: 184 (incluye Base imponible + Valor retenido
para cada concepto + totales y conceptos de pago).
"""

from __future__ import annotations


F103_CASILLERO_NAMES: dict[str, str] = {
    "302": "En relación de dependencia que supera o no la base desgravada — Base imponible",
    "303": "Servicios - Honorarios profesionales — Base imponible",
    "304": "Servicios - Predomina el intelecto — Base imponible",
    "307": "Servicios - Predomina la mano de obra. — Base imponible",
    "308": "Servicios - Utilización o aprovechamiento de la imagen o renombre — Base imponible",
    "309": "Servicios - Publicidad y comunicación — Base imponible",
    "310": "Transporte privado de pasajeros o servicio público o privado de carga — Base imponible",
    "311": "A través de liquidaciones de compra (nivel cultural o rusticidad) — Base imponible",
    "312": "Transferencia de bienes muebles de naturaleza corporal — Base imponible",
    "314": "Por regalías, derechos de autor, marcas, patentes y similares — Base imponible",
    "319": "Arrendamiento – Mercantil — Base imponible",
    "320": "Arrendamiento - Bienes inmuebles — Base imponible",
    "322": "Seguros y reaseguros (primas y cesiones) — Base imponible",
    "323": "Rendimientos financieros — Base imponible",
    "324": "Rendimientos financieros entre instituciones del sistema financiero y entidades economía popular y solidaria — Base imponible",
    "325": "Anticipo dividendos — Base imponible",
    "326": "Dividendos distribuidos que correspondan al impuesto a la renta único establecido en el art. 27 de la LRTI — Base imponible",
    "327": "Dividendos distribuidos a personas naturales residentes — Base imponible",
    "328": "Dividendos distribuidos a sociedades residentes — Base imponible",
    "329": "Dividendos distribuidos a fideicomisos residentes — Base imponible",
    "330": "Dividendos gravados distribuidos en acciones (reinversión de utilidades sin derecho a reducción tarifa IR) — Base imponible",
    "331": "Dividendos en acciones (capitalización de utilidades) — Base imponible",
    "332": "Pagos de bienes y servicios no sujetos a retención — Base imponible",
    "333": "Ganancia en la enajenación de derechos representativos de capital u otros derechos que permitan la exploración, explotación, concesión o similares de sociedades, que se coticen en las bolsas de valores del Ecuador — Base imponible",
    "334": "Contraprestación en la enajenación de derechos representativos de capital u otros derechos que permitan la exploración, explotación, concesión o similares de sociedades, no cotizados en las bolsas de valores del Ecuador — Base imponible",
    "335": "Loterías, rifas, apuestas y similares — Base imponible",
    "336": "Venta de combustibles - A comercializadoras — Base imponible",
    "337": "Venta de combustibles - A distribuidores — Base imponible",
    "338": "Compra local de banano a productor — Base imponible",
    "339": "Liquidación impuesto único a la venta local de banano de producción propia — Base imponible",
    "340": "Impuesto único a la exportación de banano de producción propia - componente 1 — Base imponible",
    "341": "Impuesto único a la exportación de banano de producción propia - componente 2 — Base imponible",
    "342": "Impuesto único a la exportación de banano producido por terceros — Base imponible",
    "343": "Otras retenciones - Aplicables el 1% — Base imponible",
    "344": "Otras retenciones - Aplicables el 2% — Base imponible",
    "345": "Otras retenciones - Aplicables el 2,75% — Base imponible",
    "346": "Otras retenciones - Aplicables a otros porcentajes. — Base imponible",
    "348": "Impuesto único a ingresos provenientes de actividades agropecuarias en etapa de producción / comercialización local o exportación — Base imponible",
    "349": "SUBTOTAL OPERACIONES EFECTUADAS EN EL PAÍS",
    "350": "Otras autorretenciones — Base imponible",
    "352": "En relación de dependencia que supera o no la base desgravada — Valor retenido",
    "353": "Servicios - Honorarios profesionales — Valor retenido",
    "354": "Servicios - Predomina el intelecto — Valor retenido",
    "357": "Servicios - Predomina la mano de obra. — Valor retenido",
    "358": "Servicios - Utilización o aprovechamiento de la imagen o renombre — Valor retenido",
    "359": "Servicios - Publicidad y comunicación — Valor retenido",
    "360": "Transporte privado de pasajeros o servicio público o privado de carga — Valor retenido",
    "361": "A través de liquidaciones de compra (nivel cultural o rusticidad) — Valor retenido",
    "362": "Transferencia de bienes muebles de naturaleza corporal — Valor retenido",
    "364": "Por regalías, derechos de autor, marcas, patentes y similares — Valor retenido",
    "369": "Arrendamiento – Mercantil — Valor retenido",
    "370": "Arrendamiento - Bienes inmuebles — Valor retenido",
    "372": "Seguros y reaseguros (primas y cesiones) — Valor retenido",
    "373": "Rendimientos financieros — Valor retenido",
    "374": "Rendimientos financieros entre instituciones del sistema financiero y entidades economía popular y solidaria — Valor retenido",
    "375": "Anticipo dividendos — Valor retenido",
    "376": "Dividendos distribuidos que correspondan al impuesto a la renta único establecido en el art. 27 de la LRTI — Valor retenido",
    "377": "Dividendos distribuidos a personas naturales residentes — Valor retenido",
    "378": "Dividendos distribuidos a sociedades residentes — Valor retenido",
    "379": "Dividendos distribuidos a fideicomisos residentes — Valor retenido",
    "380": "Dividendos gravados distribuidos en acciones (reinversión de utilidades sin derecho a reducción tarifa IR) — Valor retenido",
    "383": "Ganancia en la enajenación de derechos representativos de capital u otros derechos que permitan la exploración, explotación, concesión o similares de sociedades, que se coticen en las bolsas de valores del Ecuador — Valor retenido",
    "384": "Contraprestación en la enajenación de derechos representativos de capital u otros derechos que permitan la exploración, explotación, concesión o similares de sociedades, no cotizados en las bolsas de valores del Ecuador — Valor retenido",
    "385": "Loterías, rifas, apuestas y similares — Valor retenido",
    "386": "Venta de combustibles - A comercializadoras — Valor retenido",
    "387": "Venta de combustibles - A distribuidores — Valor retenido",
    "388": "Compra local de banano a productor — Valor retenido",
    "389": "Liquidación impuesto único a la venta local de banano de producción propia — Valor retenido",
    "390": "Impuesto único a la exportación de banano de producción propia - componente 1 — Valor retenido",
    "391": "Impuesto único a la exportación de banano de producción propia - componente 2 — Valor retenido",
    "392": "Impuesto único a la exportación de banano producido por terceros — Valor retenido",
    "393": "Otras retenciones - Aplicables el 1% — Valor retenido",
    "394": "Otras retenciones - Aplicables el 2% — Valor retenido",
    "395": "Otras retenciones - Aplicables el 2,75% — Valor retenido",
    "396": "Otras retenciones - Aplicables a otros porcentajes. — Valor retenido",
    "398": "Impuesto único a ingresos provenientes de actividades agropecuarias en etapa de producción / comercialización local o exportación — Valor retenido",
    "399": "SUBTOTAL OPERACIONES EFECTUADAS EN EL PAÍS — Valor retenido",
    "400": "Otras autorretenciones — Valor retenido",
    "402": "Con convenio de doble tributación - Intereses por financiamiento de proveedores — Base imponible",
    "403": "Con convenio de doble tributación - Intereses de créditos — Base imponible",
    "404": "Con convenio de doble tributación - Anticipo de dividendos — Base imponible",
    "405": "Con convenio de doble tributación - Anticipo de dividendos — Base imponible",
    "406": "Con convenio de doble tributación - Dividendos distribuidos a sociedades — Base imponible",
    "407": "Con convenio de doble tributación - Dividendos distribuidos a fideicomisos — Base imponible",
    "408": "Con convenio de doble tributación - Pago a no residentes - Enajenación de derechos representativos de capital u otros derechos que permitan la exploración, explotación, concesión o similares de sociedades — Base imponible",
    "409": "Con convenio de doble tributación - Seguros y reaseguros (primas y cesiones) — Base imponible",
    "410": "Con convenio de doble tributación - Servicios técnicos, administrativos o de consultoría y regalías — Base imponible",
    "411": "Con convenio de doble tributación - Otros conceptos de ingresos gravados — Base imponible",
    "412": "Con convenio de doble tributación - Otros pagos al exterior no sujetos a retención — Base imponible",
    "413": "Sin convenio de doble tributación - Intereses por financiamiento de proveedores — Base imponible",
    "414": "Sin convenio de doble tributación - Intereses de créditos — Base imponible",
    "415": "Sin convenio de doble tributación - Anticipo de dividendos — Base imponible",
    "416": "Sin convenio de doble tributación - Anticipo de dividendos — Base imponible",
    "417": "Sin convenio de doble tributación - Dividendos distribuidos a sociedades — Base imponible",
    "418": "Sin convenio de doble tributación - Dividendos distribuidos a fideicomisos — Base imponible",
    "419": "Sin convenio de doble tributación - Pago a no residentes - Enajenación de derechos representativos de capital u otros derechos que permitan la exploración, explotación, concesión o similares de sociedades — Base imponible",
    "420": "Sin convenio de doble tributación - Seguros y reaseguros (primas y cesiones) — Base imponible",
    "421": "Sin convenio de doble tributación - Servicios técnicos, administrativos o de consultoría y regalías — Base imponible",
    "422": "Sin convenio de doble tributación - Otros conceptos de ingresos gravados — Base imponible",
    "423": "Sin convenio de doble tributación - Otros pagos al exterior no sujetos a retención — Base imponible",
    "424": "En paraísos fiscales o regímenes fiscales preferentes - Intereses — Base imponible",
    "425": "En paraísos fiscales o regímenes fiscales preferentes - Anticipo de dividendos — Base imponible",
    "426": "En paraísos fiscales o regímenes fiscales preferentes - Dividendos distribuidos a personas naturales — Base imponible",
    "427": "En paraísos fiscales o regímenes fiscales preferentes - Dividendos distribuidos a sociedades — Base imponible",
    "428": "En paraísos fiscales o regímenes fiscales preferentes - Dividendos distribuidos a fideicomisos — Base imponible",
    "429": "En paraísos fiscales o regímenes fiscales preferentes - Pago a no residentes - Enajenación de derechos representativos de capital u otros derechos que permitan la exploración, explotación, concesión o similares de sociedades — Base imponible",
    "430": "En paraísos fiscales o regímenes fiscales preferentes - Pago a no residentes - Enajenación de derechos representativos de capital u otros derechos que permitan la exploración, explotación, concesión o similares de sociedades — Base imponible",
    "431": "En paraísos fiscales o regímenes fiscales preferentes - Servicios técnicos, administrativos o de consultoría y regalías — Base imponible",
    "432": "En paraísos fiscales o regímenes fiscales preferentes - Otros conceptos de ingresos gravados — Base imponible",
    "433": "En paraísos fiscales o regímenes fiscales preferentes - Otros pagos al exterior no sujetos a retención — Base imponible",
    "452": "Con convenio de doble tributación - Intereses por financiamiento de proveedores — Valor retenido",
    "453": "Con convenio de doble tributación - Intereses de créditos — Valor retenido",
    "454": "Con convenio de doble tributación - Anticipo de dividendos — Valor retenido",
    "456": "Con convenio de doble tributación - Dividendos distribuidos a sociedades — Valor retenido",
    "457": "Con convenio de doble tributación - Dividendos distribuidos a fideicomisos — Valor retenido",
    "458": "Con convenio de doble tributación - Pago a no residentes - Enajenación de derechos representativos de capital u otros derechos que permitan la exploración, explotación, concesión o similares de sociedades — Valor retenido",
    "459": "Con convenio de doble tributación - Seguros y reaseguros (primas y cesiones) — Valor retenido",
    "460": "Con convenio de doble tributación - Servicios técnicos, administrativos o de consultoría y regalías — Valor retenido",
    "461": "Con convenio de doble tributación - Otros conceptos de ingresos gravados — Valor retenido",
    "463": "Sin convenio de doble tributación - Intereses por financiamiento de proveedores — Valor retenido",
    "464": "Sin convenio de doble tributación - Intereses de créditos — Valor retenido",
    "465": "Sin convenio de doble tributación - Anticipo de dividendos — Valor retenido",
    "467": "Sin convenio de doble tributación - Dividendos distribuidos a sociedades — Valor retenido",
    "468": "Sin convenio de doble tributación - Dividendos distribuidos a fideicomisos — Valor retenido",
    "469": "Sin convenio de doble tributación - Pago a no residentes - Enajenación de derechos representativos de capital u otros derechos que permitan la exploración, explotación, concesión o similares de sociedades — Valor retenido",
    "470": "Sin convenio de doble tributación - Seguros y reaseguros (primas y cesiones) — Valor retenido",
    "471": "Sin convenio de doble tributación - Servicios técnicos, administrativos o de consultoría y regalías — Valor retenido",
    "472": "Sin convenio de doble tributación - Otros conceptos de ingresos gravados — Valor retenido",
    "474": "En paraísos fiscales o regímenes fiscales preferentes - Intereses — Valor retenido",
    "475": "En paraísos fiscales o regímenes fiscales preferentes - Anticipo de dividendos — Valor retenido",
    "476": "En paraísos fiscales o regímenes fiscales preferentes - Dividendos distribuidos a personas naturales — Valor retenido",
    "477": "En paraísos fiscales o regímenes fiscales preferentes - Dividendos distribuidos a sociedades — Valor retenido",
    "478": "En paraísos fiscales o regímenes fiscales preferentes - Dividendos distribuidos a fideicomisos — Valor retenido",
    "479": "En paraísos fiscales o regímenes fiscales preferentes - Pago a no residentes - Enajenación de derechos representativos de capital u otros derechos que permitan la exploración, explotación, concesión o similares de sociedades — Valor retenido",
    "480": "reaseguros (primas y cesiones) — Valor retenido",
    "481": "En paraísos fiscales o regímenes fiscales preferentes - Servicios técnicos, administrativos o de consultoría y regalías — Valor retenido",
    "482": "En paraísos fiscales o regímenes fiscales preferentes - Otros conceptos de ingresos gravados — Valor retenido",
    "497": "SUBTOTAL OPERACIONES EFECTUADAS CON EL EXTERIOR",
    "498": "SUBTOTAL OPERACIONES EFECTUADAS CON EL EXTERIOR — Valor retenido",
    "499": "TOTAL DE RETENCIÓN DEL IMPUESTO A LA RENTA",
    "510": "Compra local de banano a productor",
    "520": "Liquidación impuesto único a la venta local de banano de producción propia",
    "530": "Impuesto único a la exportación de banano de producción propia - componente 1",
    "540": "Impuesto único a la exportación de banano de producción propia - componente 2",
    "550": "Impuesto único a la exportación de banano producido por terceros",
    "880": "Pago directo en cuenta única del tesoro nacional (uso exclusivo para instituciones y empresas del sector público autorizadas)",
    "890": "Pago previo",
    "897": "Detalle de imputación al pago — Interés",
    "898": "Detalle de imputación al pago — Impuesto",
    "899": "Detalle de imputación al pago — Multa",
    "902": "TOTAL IMPUESTO A PAGAR",
    "903": "Interés por mora",
    "904": "Multa",
    "999": "TOTAL PAGADO",
    "3120": "Transferencia de bienes muebles de naturaleza corporal — Base imponible",
    "3380": "Producción y venta local de banano producido o no por el mismo sujeto pasivo — Base imponible",
    "3400": "Impuesto único a la exportación de banano — Base imponible",
    "3440": "Otras retenciones - Aplicables el 2,75% — Base imponible",
    "3480": "Impuesto a la renta único sobre los ingresos percibidos por los operadores de pronósticos deportivos — Base imponible",
    "3620": "Transferencia de bienes muebles de naturaleza corporal — Valor retenido",
    "3880": "Producción y venta local de banano producido o no por el mismo sujeto pasivo — Valor retenido",
    "3900": "Impuesto único a la exportación de banano — Valor retenido",
    "3940": "Otras retenciones - Aplicables el 2,75% — Valor retenido",
    "3980": "Impuesto a la renta único sobre los ingresos percibidos por los operadores de pronósticos deportivos — Valor retenido",
    "4050": "Con convenio de doble tributación - Dividendos sin beneficiario efectivo persona natural residente en Ecuador — Base imponible",
    "4060": "Con convenio de doble tributación - Dividendos con beneficiario efectivo persona natural residente en Ecuador — Base imponible",
    "4070": "Con convenio de doble tributación - Dividendos incumpliendo el deber de informar la composición societaria — Base imponible",
    "4160": "Sin convenio de doble tributación - Dividendos sin beneficiario efectivo persona natural residente en Ecuador — Base imponible",
    "4170": "Sin convenio de doble tributación - Dividendos con beneficiario efectivo persona natural residente en Ecuador — Base imponible",
    "4180": "Sin convenio de doble tributación - Dividendos incumpliendo el deber de informar la composición societaria — Base imponible",
    "4260": "En paraísos fiscales o regímenes fiscales preferentes - Dividendos sin beneficiario efectivo persona natural residente en Ecuador — Base imponible",
    "4270": "En paraísos fiscales o regímenes fiscales preferentes - Dividendos con beneficiario efectivo persona natural residente en Ecuador — Base imponible",
    "4280": "En paraísos fiscales o regímenes fiscales preferentes - Dividendos incumpliendo el deber de informar la composición societaria — Base imponible",
    "4550": "Con convenio de doble tributación - Dividendos sin beneficiario efectivo persona natural residente en Ecuador — Valor retenido",
    "4560": "Con convenio de doble tributación - Dividendos con beneficiario efectivo persona natural residente en Ecuador — Valor retenido",
    "4570": "Con convenio de doble tributación - Dividendos incumpliendo el deber de informar la composición societaria — Valor retenido",
    "4660": "Sin convenio de doble tributación - Dividendos sin beneficiario efectivo persona natural residente en Ecuador — Valor retenido",
    "4670": "Sin convenio de doble tributación - Dividendos con beneficiario efectivo persona natural residente en Ecuador — Valor retenido",
    "4680": "Sin convenio de doble tributación - Dividendos incumpliendo el deber de informar la composición societaria — Valor retenido",
    "4760": "En paraísos fiscales o regímenes fiscales preferentes - Dividendos sin beneficiario efectivo persona natural residente en Ecuador — Valor retenido",
    "4770": "En paraísos fiscales o regímenes fiscales preferentes - Dividendos con beneficiario efectivo persona natural residente en Ecuador — Valor retenido",
    "4780": "En paraísos fiscales o regímenes fiscales preferentes - Dividendos incumpliendo el deber de informar la composición societaria — Valor retenido",
    "5100": "Producción y venta local de banano producido o no por el mismo sujeto pasivo",
    "5300": "Impuesto único a la exportación de banano",
}


def get_casillero_name(casillero: str, fallback: str = "") -> str:
    """Devuelve el nombre oficial del casillero F-103 según Tabla 1 SRI."""
    return F103_CASILLERO_NAMES.get(str(casillero).strip(), fallback)
