// Strings centralizadas (i18n placeholder, solo ES en MVP).
export const STRINGS = {
  catalog_title: "Pruebas de auditoría a través de herramientas",
  coming_soon: "Próximamente",
  back_to_catalog: "← Volver al catálogo",

  of_title: "Auditoría de Obligaciones Fiscales",
  of_subtitle:
    "Sube las declaraciones SRI (F-103, F-104) y mayores. Descarga el papel de trabajo Excel con DM6 IVA y DM7 Retenciones pobladas.",
  of_form_cliente: "Cliente auditado",
  of_form_periodo: "Período (ej. Ejercicio 2025)",
  of_form_period_end: "Fecha de corte",
  of_form_prepared_by: "Preparado por (opcional)",
  of_form_reviewed_by: "Revisado por (opcional)",
  of_form_firma: "Firma auditora (logo en el Excel)",
  of_firma_audit_consulting: "Audit Consulting Group",
  of_firma_partner_auditing: "Partner Auditing Cía. Ltda.",
  of_slot_f103: "F-103 Retenciones IR (PDFs mensuales) — opcional en M1",
  of_slot_f104: "F-104 IVA (PDFs mensuales) — requerido",
  of_slot_ats: "Anexo Transaccional (XML) — opcional en M1",
  of_slot_mayor_compras: "Mayor de Compras (Excel) — opcional en M1",
  of_slot_mayor_ventas: "Mayor de Ventas (Excel) — opcional en M1",
  of_slot_f101: "F-101 Renta anual (PDF) — opcional en M1",
  of_generate: "Generar papel de trabajo",
  of_processing: "Procesando…",
  of_done: "Papel de trabajo listo",
  of_download: "Descargar Excel",
  of_failed: "Falló la generación",
  of_new: "Nuevo papel de trabajo",
  of_recent: "Generados recientemente",
  of_need_pdf: "Sube al menos 1 PDF F-104 para continuar.",

  ict_title: "Informe de Cumplimiento Tributario",
  ict_subtitle:
    "Llena los datos del cliente, elige la firma y sube el Informe de Auditoría Externa y el F-101. Descarga el informe Word lleno.",
  ict_cliente: "Cliente auditado",
  ict_ejercicio: "Ejercicio fiscal (ej. 2025)",
  ict_fecha_carga_sri: "Fecha de carga del reporte de diferencias al SRI",
  ict_recomendaciones_q: "¿Existen recomendaciones sobre aspectos tributarios?",
  ict_recomendaciones_txt: "Detalle de las recomendaciones",
  ict_firma: "Firma auditora (elige la plantilla)",
  ict_slot_informe: "Informe de Auditoría Externa (PDF) — requerido",
  ict_slot_f101: "Declaración de Impuesto a la Renta F-101 (PDF) — requerido",
  ict_slot_diferencias: "Anexo de Diferencias SRI (PDF) — opcional",
  ict_fecha_emision: "Fecha de emisión del informe (auto)",
  ict_marco: "Marco contable (auto)",
  ict_fecha_declaracion: "Fecha de declaración del IR (auto)",
  ict_generate: "Generar informe",
  ict_clear: "Limpiar",
  ict_processing: "Generando informe…",
  ict_done: "Informe listo",
  ict_download: "Descargar Word",
  ict_failed: "Falló la generación",
  ict_new: "Nuevo informe",
  ict_recent: "Generados recientemente",
  ict_need_files: "Sube el Informe de Auditoría Externa y el F-101.",
};
