// Strings centralizadas (i18n placeholder, solo ES en MVP).
export const STRINGS = {
  catalog_title: "Pruebas de auditoría a través de herramientas",
  coming_soon: "Próximamente",
  back_to_catalog: "← Volver al catálogo",

  of_title: "Auditoría de Obligaciones Fiscales",
  of_subtitle:
    "Sube las declaraciones SRI (F-103, F-104) y mayores. Descarga el papel de trabajo Excel con DM6 IVA y DM7 Retenciones pobladas.",
  of_form_cliente: "Cliente auditado",
  of_form_periodo: "Período (ej. Ejercicio 2025)",
  of_form_period_end: "Fecha de corte",
  of_form_prepared_by: "Preparado por (opcional)",
  of_form_reviewed_by: "Revisado por (opcional)",
  of_form_firma: "Firma auditora (logo en el Excel)",
  of_firma_audit_consulting: "Audit Consulting Group",
  of_firma_partner_auditing: "Partner Auditing Cía. Ltda.",
  of_slot_f103: "F-103 Retenciones IR (PDFs mensuales) — opcional en M1",
  of_slot_f104: "F-104 IVA (PDFs mensuales) — requerido",
  of_slot_ats: "Anexo Transaccional (XML) — opcional en M1",
  of_slot_mayor_general: "Mayor General de Impuestos (Excel) — requerido",
  of_slot_mayor_especifico:
    "Mayor específico para prueba puntual (Excel) — opcional",
  of_mayor_especifico_categoria: "¿A qué categoría corresponde?",
  of_slot_f101: "F-101 Renta anual (PDF) — opcional en M1",
  of_slot_uploading: "Subiendo…",
  of_slot_categoria_placeholder: "Selecciona una categoría",
  of_slot_categoria_loading: "Cargando categorías…",
  of_slot_categoria_hint: "Elige la categoría antes de subir el archivo.",
  of_slot_remove_title: "Quitar archivo(s)",
  of_slot_remove_confirm:
    "¿Eliminar los archivos subidos de este documento? Podrás volver a subirlos.",
  of_generate: "Generar papel de trabajo",
  of_processing: "Procesando…",
  of_done: "Papel de trabajo listo",
  of_download: "Descargar Excel",
  of_failed: "Falló la generación",
  of_new: "Nuevo papel de trabajo",
  of_recent: "Generados recientemente",
  of_need_pdf: "Sube al menos 1 PDF F-104 para continuar.",

  // ---- Workspace de Obligaciones Fiscales (estilo ICT) ----
  of_ws_code: "OF",
  of_ws_title: "Workspace de Obligaciones Fiscales",
  of_ws_cargando: "Cargando encargo…",
  of_ws_contribuyente: "Contribuyente",
  of_ws_edit_datos: "✏ Editar datos",
  of_ws_procesar: "▶ Procesar",
  of_ws_procesando: "⏳ Procesando…",
  of_ws_procesar_disabled_sin_mayor:
    "Sube el Mayor General de Impuestos antes de procesar.",
  of_ws_procesar_disabled_no_borrador:
    "Solo se puede procesar un encargo en borrador o en revisión.",
  of_ws_descargar: "📤 Descargar Excel",
  of_ws_descargando: "⏳ Descargando…",
  of_ws_descargar_disabled:
    "Aprueba la clasificación en la pestaña Clasificación para habilitar la descarga.",
  of_ws_encerar: "🔄 Encerar",
  of_ws_encerar_confirm:
    "¿Encerar el encargo actual? Se perderán los documentos subidos y la " +
    "clasificación revisada. Esta acción no se puede deshacer.",
  of_ws_subir_documentos: "📂 Subir documentos",
  of_ws_documentos_subidos: "documentos subidos",
  of_ws_anexos_label: "de",
  of_ws_click_cedula: "Click en una cédula para ver su estado y qué documentos usa:",
  of_ws_sin_job_title: "Ningún encargo en curso",
  of_ws_sin_job_desc:
    "Crea un encargo nuevo para empezar a subir documentos y generar el papel de trabajo.",
  of_ws_nuevo_encargo: "+ Nuevo encargo",
  of_ws_error_cargar: "No se pudo cargar el encargo del proyecto.",
  of_ws_llenado_automatico_t: "Estado de la cédula",
  of_ws_llenado_automatico_d:
    "Esta cédula se genera automáticamente al aprobar la clasificación. No requiere una subida propia.",
  of_ws_docs_usados: "📄 Documentos que usa esta cédula:",

  of_tile_clasificacion_t: "Clasificación",
  of_tile_clasificacion_d: "Revisión de la clasificación del Mayor General",
  of_tile_dm3_t: "DM3 Saldos",
  of_tile_dm3_d: "Saldos por cuenta clasificados",
  of_tile_dm4_t: "DM4 Compras",
  of_tile_dm4_d: "Cédula de compras (F-104 / Mayor)",
  of_tile_dm5_t: "DM5 Ventas",
  of_tile_dm5_d: "Cédula de ventas (F-104 / Mayor)",
  of_tile_dm6_t: "DM6 IVA",
  of_tile_dm6_d: "Conciliación de IVA",
  of_tile_dm7_t: "DM7 Retenciones",
  of_tile_dm7_d: "Retenciones en la fuente (F-103)",

  // Modal de datos del encargo (crear / editar)
  of_modal_title_nuevo: "Nuevo encargo",
  of_modal_title_editar: "Editar datos del encargo",
  of_modal_crear: "Crear encargo",
  of_modal_guardar: "Guardar",
  of_modal_guardando: "Guardando…",
  of_modal_cancelar: "Cancelar",
  of_modal_editar_warning:
    "Editar estos datos borra el encargo actual (incluidos los documentos " +
    "subidos y la clasificación revisada) y crea uno nuevo con los datos " +
    "editados. ¿Continuar?",

  // Pantalla de revisión de la clasificación
  of_rev_title: "Revisión de la clasificación",
  of_rev_cargando: "Cargando clasificación…",
  of_rev_error_cargar: "No se pudo cargar la clasificación del Mayor General.",
  of_rev_sin_cuentas: "El Mayor General no arrojó cuentas para clasificar.",
  of_rev_cuentas: "cuentas",
  of_rev_requieren_revision: "requieren revisión",
  of_rev_col_codigo: "Código",
  of_rev_col_cuenta: "Cuenta",
  of_rev_col_movs: "Movs",
  of_rev_col_debe: "Debe",
  of_rev_col_haber: "Haber",
  of_rev_col_categoria: "Categoría",
  of_rev_col_confianza: "Confianza",
  of_rev_col_porque: "Por qué",
  of_rev_confianza_alta: "alta",
  of_rev_confianza_media: "media",
  of_rev_confianza_baja: "baja",
  of_rev_sugerido: "Motor sugirió:",
  of_rev_corregida: "corregida",
  of_rev_sin_justificacion: "Sin motivos registrados.",
  of_rev_ver_motivos: "Ver motivos",
  of_rev_categoria_sin_asignar: "Sin categoría",
  of_rev_guardar: "Guardar correcciones",
  of_rev_guardando: "Guardando…",
  of_rev_guardado_ok: "Correcciones guardadas.",
  of_rev_aprobar: "Aprobar y generar",
  of_rev_aprobando: "Generando…",
  of_rev_aprobar_disabled:
    "Guarda las correcciones pendientes antes de aprobar.",

  ict_title: "Informe de Cumplimiento Tributario",
  ict_subtitle:
    "Llena los datos del cliente, elige la firma y sube el Informe de Auditoría Externa y el F-101. Descarga el informe Word lleno.",
  ict_cliente: "Cliente auditado",
  ict_ejercicio: "Ejercicio fiscal (ej. 2025)",
  ict_fecha_carga_sri: "Fecha de carga del reporte de diferencias al SRI",
  ict_recomendaciones_q: "¿Existen recomendaciones sobre aspectos tributarios?",
  ict_recomendaciones_txt: "Detalle de las recomendaciones",
  ict_firma: "Firma auditora (elige la plantilla)",
  ict_slot_informe: "Informe de Auditoría Externa (PDF) — requerido",
  ict_slot_f101: "Declaración de Impuesto a la Renta F-101 (PDF) — requerido",
  ict_slot_diferencias: "Anexo de Diferencias SRI (PDF) — opcional",
  ict_fecha_emision: "Fecha de emisión del informe (auto)",
  ict_marco: "Marco contable (auto)",
  ict_fecha_declaracion: "Fecha de declaración del IR (auto)",
  ict_generate: "Generar informe",
  ict_clear: "Limpiar",
  ict_processing: "Generando informe…",
  ict_done: "Informe listo",
  ict_download: "Descargar Word",
  ict_failed: "Falló la generación",
  ict_new: "Nuevo informe",
  ict_recent: "Generados recientemente",
  ict_need_files: "Sube el Informe de Auditoría Externa y el F-101.",
};
