"""Cell map for MAPEO A1 sheet."""

A1_SHEET = "MAPEO DE LA DECLARACIÓN A1"
A1_FIRST_DATA_ROW = 13  # Verified against template: row 13 contains casillero 311

A1_HEADER_MAP = {
    "C3": "razon_social",
    "C4": "ruc",
    "C5": "ejercicio_fiscal",
    "C6": "numero_adhesivo",
}

A1_CASILLEROS_ORDERED: list[tuple[str, str]] = [
    ("311", "EFECTIVO Y EQUIVALENTES AL EFECTIVO"),
    ("315", "CUENTAS Y DOCUMENTOS POR COBRAR CORRIENTES"),
    ("325", "OTRAS CUENTAS Y DOCUMENTOS POR COBRAR CORRIENTES"),
    ("336", "ACTIVOS POR IMPUESTOS CORRIENTES / Crédito Tributario IVA"),
    ("337", "ACTIVOS POR IMPUESTOS CORRIENTES / Crédito Tributario Renta"),
    ("339", "INVENTARIOS - Mercaderías en tránsito"),
    ("342", "Inventario de prod. term. y mercad. en almacén"),
    ("343", "Inventario de suministros, herramientas, repuestos"),
    ("358", "GASTOS PAGADOS POR ANTICIPADO - PRIMAS DE SEGURO"),
    ("359", "GASTOS PAGADOS POR ANTICIPADO - OTROS PREPAGADOS"),
    ("361", "TOTAL ACTIVOS CORRIENTES"),
    ("362", "TERRENOS"),
    ("364", "EDIFICIOS Y OTROS INMUEBLES"),
    ("368", "MAQUINARIA, EQUIPO, INSTALACIONES Y ADECUACIONES"),
    ("374", "EQUIPO DE COMPUTACIÓN"),
    ("384", "(-) DEPRECIACIÓN ACUMULADA DE PROPIEDADES, PLANTA Y EQUIPO"),
    ("432", "CUENTAS Y DOCUMENTOS POR COBRAR NO CORRIENTES"),
    ("440", "ACTIVOS POR IMPUESTOS DIFERIDOS"),
    ("449", "TOTAL ACTIVOS NO CORRIENTES"),
    ("499", "TOTAL DEL ACTIVO"),
    ("513", "CUENTAS Y DOCUMENTOS POR PAGAR CORRIENTES - PROVEEDORES LOCALES"),
    ("514", "CUENTAS Y DOCUMENTOS POR PAGAR CORRIENTES - PROVEEDORES EXTERIOR"),
    ("521", "OTRAS CUENTAS Y DOCUMENTOS POR PAGAR CORRIENTES"),
    ("533", "PARTICIPACIÓN TRABAJADORES POR PAGAR DEL EJERCICIO"),
    ("534", "OBLIGACIONES CON EL IESS"),
    ("536", "OTROS PASIVOS CORRIENTES POR BENEFICIOS A EMPLEADOS"),
    ("545", "PASIVOS POR INGRESOS DIFERIDOS - Anticipos clientes"),
    ("549", "OTROS PASIVOS CORRIENTES"),
    ("569", "TOTAL PASIVOS CORRIENTES"),
    ("601", "CAPITAL SUSCRITO Y/O ASIGNADO"),
    ("604", "APORTES DE SOCIOS PARA FUTURA CAPITALIZACIÓN"),
    ("609", "RESERVA LEGAL"),
    ("613", "RESULTADOS ACUMULADOS"),
    ("615", "RESULTADO DEL EJERCICIO"),
    ("699", "TOTAL PATRIMONIO"),
    ("6001", "VENTAS NETAS LOCALES GRAVADAS"),
    ("6005", "VENTAS NETAS EXPORTACIONES"),
    ("6999", "TOTAL INGRESOS"),
]
