"""Cell map for INVENTARIOS A9 sheet."""

A9_SHEET = "INVENTARIOS A9"

A9_HEADER_MAP = {
    "C3": "razon_social",
    "C4": "ruc",
    "C5": "ejercicio_fiscal",
    "C6": "numero_adhesivo",
}

# 9 fixed casilleros (validated against actual template rows 18-26)
A9_CASILLEROS = {
    18: "7001",  # INVENTARIO INICIAL DE BIENES NO PRODUCIDOS
    19: "7010",  # INVENTARIO FINAL DE BIENES NO PRODUCIDOS
    20: "7013",  # INVENTARIO INICIAL DE MATERIA PRIMA
    21: "7022",  # INVENTARIO FINAL DE MATERIA PRIMA
    22: "7025",  # INVENTARIO INICIAL DE PRODUCTOS EN PROCESO
    23: "7028",  # INVENTARIO FINAL DE PRODUCTOS EN PROCESO
    24: "7031",  # INVENTARIO INICIAL PRODUCTOS TERMINADOS
    25: "7034",  # INVENTARIO FINAL DE PRODUCTOS TERMINADOS
    26: "7037",  # AJUSTES
}
